window.SAT_DAYS = window.SAT_DAYS || [];
window.SAT_DAYS.push(
{
  day: 11, date: "2026-09-29",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The diplomat’s smile was ______: it lasted long enough for the cameras and vanished the moment the doors closed." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "perfunctory", B: "spontaneous", C: "eternal", D: "bashful" }, answer: "A", explain: { correct: "Perfunctory means done as a routine, without real feeling—a camera-only smile.", wrong: { B: "Spontaneous smiles are unplanned, not timed to cameras.", C: "Eternal would not vanish at the door.", D: "Bashful means shy; this smile is performed, not timid." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Ecologists had to ______ their model when frogs appeared in ponds the model had labeled lifeless." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "revise", B: "copyright", C: "ignore", D: "frame" }, answer: "A", explain: { correct: "Revise means change after new evidence; frogs in “lifeless” ponds force a model update.", wrong: { B: "Copyright is legal ownership, not scientific correction.", C: "Ignoring frogs would not respond to the contradiction.", D: "Frame does not mean correct a model." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The memoir’s power lies in its ______ details: a burnt pan, a bus transfer, a voicemail never played." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "homely", B: "imperial", C: "abstract", D: "statistical" }, answer: "A", explain: { correct: "Homely here means everyday and unpretentious; burnt pans and bus transfers are ordinary particulars.", wrong: { B: "Imperial suggests grandeur, unlike kitchen and transit details.", C: "Abstract would avoid concrete objects.", D: "Statistical details would be numbers, not a voicemail." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Critics called the plan ______ because it assumed unlimited water in a basin already under restriction." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "quixotic", B: "prudent", C: "overdue", D: "unwritten" }, answer: "A", explain: { correct: "Quixotic means unrealistically idealistic; unlimited water against restrictions fits.", wrong: { B: "Prudent means careful, unlike an impossible water assumption.", C: "Overdue means late, not unrealistic.", D: "Unwritten concerns documentation, not feasibility." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The two accounts of the riot were not merely different; they were ______, each denying events the other treated as central." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "irreconcilable", B: "identical", C: "poetic", D: "brief" }, answer: "A", explain: { correct: "Irreconcilable means cannot be made consistent; mutual denial of core events fits.", wrong: { B: "Identical accounts would match.", C: "Poetic is a style, not a logical clash.", D: "Brief describes length, not contradiction." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "She refused to ______ the interviewer’s premise that success requires a single hometown, listing instead four cities that had shaped the work." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "accept", B: "record", C: "film", D: "translate" }, answer: "A", explain: { correct: "Accept the premise means take it as true; listing four cities rejects that single-hometown claim.", wrong: { B: "Record would not be refused by listing cities.", C: "Film is production, not agreement.", D: "Translate is about language." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A tide chart is a promise with an asterisk. Wind can pile water higher than the printed high. A sailor who treats the number as destiny, not as a starting guess, will someday tie a boat to a piling that disappears." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To warn that printed tide heights are estimates subject to weather", B: "To sell a brand of rope", C: "To narrate one sailor’s childhood", D: "To deny that tides exist" }, answer: "A", explain: { correct: "The asterisk, wind, and disappearing piling all limit trust in the printed number.", wrong: { B: "No product is sold.", C: "No childhood story appears.", D: "Tides are assumed real." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "The opening paragraph dazzles. The middle sags under three similar anecdotes. The ending recovers by returning to the first image. Structure, here, is not a mystery: peak, trough, echo." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "It maps another text’s shape and then names that shape", B: "It provides a chemical formula", C: "It is a legal contract", D: "It lists train times" }, answer: "A", explain: { correct: "The sentences walk through opening, middle, ending, then label peak-trough-echo.", wrong: { B: "No formula appears.", C: "This is criticism, not a contract.", D: "No schedule appears." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "We say a species is “discovered” when a paper is published. Local names often predates that paper by centuries. Discovery, in the scientific sense, is a filing event, not the first human encounter." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It defines “discovery” more narrowly after contrasting it with local knowledge", B: "It lists every local name for one bird", C: "It argues that papers should not be published", D: "It describes how to file taxes" }, answer: "A", explain: { correct: "After noting older local names, the last sentence restricts scientific “discovery” to publication.", wrong: { B: "No name list appears.", C: "Publication is used as a criterion, not banned.", D: "Filing is metaphorical, not tax advice." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Single-use plastic bans work when substitutes are already cheap. Where they are not, people reuse banned bags illegally or switch to thicker plastics that weigh more in landfills." }, { label: "Text 2", body: "Bans are signals. Even a leaky ban tells firms that the next product line should not rely on throwaway film. Leakage is real; so is the redesign that follows a clear rule." }], prompt: "Which choice best describes the difference between the two texts?", choices: { A: "Text 1 stresses substitution problems; Text 2 treats leakage as compatible with long-run redesign", B: "Text 1 supports all plastics; Text 2 bans all packaging", C: "Both deny that landfills exist", D: "Text 2 is only about metal straws" }, answer: "A", explain: { correct: "Text 1 focuses on illegal reuse and heavier substitutes. Text 2 admits leakage but values the signal to redesign.", wrong: { B: "Neither takes those extreme positions.", C: "Text 1 mentions landfills as real.", D: "Text 2 is about throwaway film and rules generally." } } }
  ]
},
{
  day: 12, date: "2026-09-30",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The indictment was unusually ______, quoting emails rather than paraphrasing them into milder language." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "direct", B: "coy", C: "musical", D: "undated" }, answer: "A", explain: { correct: "Direct means straightforward; quoting emails instead of softening them is blunt.", wrong: { B: "Coy means shyly indirect, the opposite of quoting.", C: "Musical is irrelevant.", D: "Undated concerns dates, not tone." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Because the trail was ______, rangers posted a notice that only experienced hikers should attempt the last mile." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "arduous", B: "paved", C: "crowded with benches", D: "theoretical" }, answer: "A", explain: { correct: "Arduous means strenuous; a last mile limited to experienced hikers fits.", wrong: { B: "Paved trails are usually easier.", C: "Benches suggest an easier path.", D: "Theoretical trails are not hiked." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "His footnotes ______ the main argument: instead of supporting claims, they wander into unrelated family stories." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "undermine", B: "bolster", C: "translate", D: "number" }, answer: "A", explain: { correct: "Undermine means weaken; wandering notes fail to support claims.", wrong: { B: "Bolster means strengthen, which wandering stories do not do.", C: "Translate is about language.", D: "Number is merely sequencing." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "The cease-fire remained ______ as long as both armies kept their artillery a valley apart." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "fragile", B: "eternal", C: "irrelevant", D: "unwritten only" }, answer: "A", explain: { correct: "Fragile means easily broken; it holds only while guns stay apart.", wrong: { B: "Eternal would not depend on a temporary gap.", C: "A cease-fire in force is not irrelevant.", D: "The issue is stability, not whether it was written." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "What the restoration ______ was a second signature beneath the varnish, changing the painting’s attribution overnight." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "uncovered", B: "invented", C: "sang", D: "insured" }, answer: "A", explain: { correct: "Uncovered means revealed; a hidden signature appearing in restoration fits.", wrong: { B: "Invented would mean the signature was faked by restorers, which the sentence does not say.", C: "Sang is unrelated.", D: "Insured is financial." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Voters were ______ of slogans after a year of ads that never named a budget number." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "weary", B: "enamored", C: "unaware", D: "proud" }, answer: "A", explain: { correct: "Weary means tired of; empty ads would fatigue voters.", wrong: { B: "Enamored means fond of slogans, unlike fatigue.", C: "They have heard a year of ads, so they are aware.", D: "Proud of slogans would not follow from missing budgets." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A glossary at the back of a novel is a confession. It admits that the main text did not make certain words earn their keep. Sometimes that confession is a gift to outsiders. Sometimes it is a failure of the pages that came first." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To interpret a glossary as both aid and possible sign of earlier failure", B: "To teach alphabetization", C: "To ban novels with glossaries", D: "To review a specific dictionary" }, answer: "A", explain: { correct: "“Confession,” “gift,” and “failure” hold both uses of a glossary.", wrong: { B: "No alphabet lesson appears.", C: "No ban is issued.", D: "No particular dictionary is reviewed." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "Count the verbs in a campaign speech. If they are all “fight,” “stand,” and “believe,” you have learned the candidate’s preferred music. You have not learned a schedule." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It states what the verb-counting exercise cannot provide", B: "It lists rally dates", C: "It praises all campaign speeches", D: "It explains English grammar rules in full" }, answer: "A", explain: { correct: "After saying you learn “music,” the last sentence denies that you learn a schedule—i.e., a plan.", wrong: { B: "No dates appear.", C: "The tone is diagnostic, not praise.", D: "Only a method is sketched, not a full grammar." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "First the river was straightened. Then farms filled the old bends. Then a flood had nowhere to sit, so it sat in living rooms. The straight line was sold as control. It redistributed the water instead." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "A causal sequence followed by a reinterpretation of “control”", B: "A recipe for bread", C: "A character sketch of a mayor", D: "A table of rainfall totals" }, answer: "A", explain: { correct: "Straighten, farms, flood in houses, then the twist that control was redistribution.", wrong: { B: "No recipe appears.", C: "No person is profiled.", D: "No table appears." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Open-office plans increase chance encounters, which managers treat as a proxy for collaboration. Measured deep-work hours, however, fall." }, { label: "Text 2", body: "Encounters are not collaboration. Collaboration has a deliverable. A hallway chat that never changes a file is atmosphere. Design the office around the work product, not around the possibility of bumping into someone." }], prompt: "The author of Text 2 would most likely say that Text 1’s managers are", choices: { A: "mistaking proximity for actual joint work", B: "correct that deep work does not matter", C: "focused only on remote software", D: "uninterested in offices" }, answer: "A", explain: { correct: "Text 2 defines collaboration as a deliverable and treats chats as atmosphere, so managers using encounters as a proxy are confused.", wrong: { B: "Text 1 notes deep-work hours falling, which Text 2 would not dismiss.", C: "Offices, not remote tools, are the topic.", D: "Both discuss office design." } } }
  ]
},
{
  day: 13, date: "2026-10-01",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The comedian’s later specials are more ______: fewer punch lines per minute, more silence after a hard observation." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "restrained", B: "frantic", C: "inaccurate", D: "commercial" }, answer: "A", explain: { correct: "Restrained means held back; fewer punch lines and more silence fit.", wrong: { B: "Frantic would increase pace, not silence.", C: "Inaccurate concerns truth, not density of jokes.", D: "Commercial concerns sales, not timing." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Historians still ______ over whether the letter is genuine; the ink matches the period, but the handwriting does not." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "debate", B: "agree completely", C: "sing", D: "profit" }, answer: "A", explain: { correct: "Debate means argue both sides; mixed evidence on ink versus handwriting fits.", wrong: { B: "Complete agreement is blocked by the handwriting problem.", C: "Sing is unrelated.", D: "Profit is financial." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The new ordinance was ______: it banned “excessive noise” without defining a decibel level or a time of day." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "vague", B: "stringent", C: "bilingual", D: "popular" }, answer: "A", explain: { correct: "Vague means unclear; no decibel or hour makes the ban hard to apply.", wrong: { B: "Stringent means strict and specific, unlike a missing threshold.", C: "Bilingual concerns languages.", D: "Popular is about approval." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "To ______ the species, biologists moved a small group to an island free of the invasive snake." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "safeguard", B: "exhibit only", C: "hunt", D: "rename" }, answer: "A", explain: { correct: "Safeguard means protect; a snake-free island is a protection measure.", wrong: { B: "Exhibit only would be display, not a conservation move.", C: "Hunt would harm the species.", D: "Rename does not require an island." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "Her praise was so ______—“fine,” “adequate,” “not bad”—that the cast could not tell whether the show had worked." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "tepid", B: "effusive", C: "musical", D: "public" }, answer: "A", explain: { correct: "Tepid means lukewarm; mild adjectives that withhold a verdict fit.", wrong: { B: "Effusive praise would gush.", C: "Musical is unrelated.", D: "Public concerns audience, not warmth of adjectives." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "The two data sets were ______, so the team could not merge them without inventing a common set of categories first." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "incompatible", B: "identical", C: "colorful", D: "short" }, answer: "A", explain: { correct: "Incompatible means they cannot work together as is; needing new shared categories fits.", wrong: { B: "Identical sets would merge easily.", C: "Colorful is visual, not structural.", D: "Short describes length, not mergeability." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A caption that says “untouched wilderness” under a photo of a managed forest is not a small error. It trains viewers to miss the stumps, the roads, and the people who have worked that land. Words around an image are part of the image." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To argue that captions shape what viewers believe they are seeing", B: "To sell camera equipment", C: "To deny that forests exist", D: "To narrate a hiking trip" }, answer: "A", explain: { correct: "The false “wilderness” caption and “words around an image” claim make captioning the issue.", wrong: { B: "No gear is sold.", C: "Forests are assumed real.", D: "No trip is narrated." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "The committee listed three options, then spent nine pages on the first and two sentences on the others. Proportional ink is a kind of vote." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It generalizes that page space itself signals preference", B: "It adds a fourth option", C: "It explains printing costs", D: "It praises brevity in all cases" }, answer: "A", explain: { correct: "“Proportional ink is a kind of vote” names what the lopsided pages were doing.", wrong: { B: "No new option appears.", C: "Cost is not discussed.", D: "The point is imbalance, not a hymn to brevity." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Take a familiar proverb. Invert it. Test the inversion against a case. If “look before you leap” fails when hesitation costs a rescue, you have not destroyed the proverb. You have found its border." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "A method of testing sayings, then a claim about what failure actually shows", B: "A biography of a proverb’s author", C: "A swimming lesson", D: "A court transcript" }, answer: "A", explain: { correct: "Invert, test, then “border” rather than destruction.", wrong: { B: "No author biography appears.", C: "Leap is metaphorical.", D: "No transcript appears." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Students should write first drafts by hand. Slower production improves sentence-level attention, and phones stay in another room." }, { label: "Text 2", body: "Hand drafting helps some writers and excludes others, including many with dysgraphia. The aim is attention, not nostalgia for pens. A locked-down laptop can isolate a writer from the phone without punishing handwriting speed." }], prompt: "How would Text 2 most likely respond to Text 1?", choices: { A: "By keeping the goal of attention but rejecting handwriting as the only tool", B: "By insisting phones belong on the desk", C: "By denying that drafts exist", D: "By claiming all students prefer pens" }, answer: "A", explain: { correct: "Text 2 names attention as the aim and offers a locked-down laptop as another way to get it.", wrong: { B: "Text 2 still wants isolation from phones.", C: "Both assume drafting.", D: "Text 2 notes that handwriting excludes some students." } } }
  ]
},
{
  day: 14, date: "2026-10-02",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The novel’s villain is not ______; her motives are explained, even if they remain morally unacceptable." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "inscrutable", B: "talkative", C: "wealthy", D: "minor" }, answer: "A", explain: { correct: "Inscrutable means impossible to understand; explained motives mean she is not that.", wrong: { B: "Talkative is about speech volume, not understood motives.", C: "Wealth is not the issue.", D: "Minor status is not about motives." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Engineers ______ the old supports rather than replace the whole span, shaving months off the closure." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "reinforced", B: "ignored", C: "photographed only", D: "named" }, answer: "A", explain: { correct: "Reinforced means strengthened; keeping the span and shortening closure fits.", wrong: { B: "Ignoring supports would not shorten a safe closure.", C: "Photos alone would not shave months by fixing structure.", D: "Named is irrelevant." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The witness’s story remained ______ across three hearings; only the order of two minor details changed." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "consistent", B: "contradictory", C: "silent", D: "rhymed" }, answer: "A", explain: { correct: "Consistent means stable; tiny order changes with a stable story fit.", wrong: { B: "Contradictory would mean major clashes.", C: "The witness told a story, so not silent.", D: "Rhymed concerns poetry." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Activists argued that the statue ______ a narrow version of the city’s past by centering one merchant and omitting the people he had enslaved." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "enshrined", B: "erased completely from maps", C: "cleaned", D: "insured" }, answer: "A", explain: { correct: "Enshrined means preserved as honored; a statue centering one merchant does that for a narrow past.", wrong: { B: "The statue is present, not absent from maps.", C: "Cleaned is maintenance.", D: "Insured is financial." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The dataset was ______ with duplicates, so the first cleaning step was to collapse repeated IDs." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "riddled", B: "empty", C: "alphabetical", D: "secret" }, answer: "A", explain: { correct: "Riddled with means full of; duplicates forcing a collapse step fit.", wrong: { B: "Empty would have no IDs.", C: "Alphabetical is a sort order.", D: "Secret is about access." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Her conclusion was ______: it followed from the table, without a leap to a policy the table could not support." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "warranted", B: "gratuitous", C: "unreadable", D: "humorous" }, answer: "A", explain: { correct: "Warranted means justified; a conclusion that stays within the table is justified.", wrong: { B: "Gratuitous means unearned or extra.", C: "Unreadable concerns clarity of prose.", D: "Humorous is tone." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "When a museum labels an object “anonymous artist,” ask who refused to record a name. Anonymity can be a gap in the paperwork. It can also be a decision about whose labor counted as art." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To push readers to treat “anonymous” as a historical question, not a neutral blank", B: "To list every anonymous painting in one museum", C: "To explain oil-paint chemistry", D: "To advertise a naming contest" }, answer: "A", explain: { correct: "The text asks who refused to record a name and offers gap versus decision.", wrong: { B: "No inventory appears.", C: "No chemistry appears.", D: "No contest appears." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "A graph without a scale is an illustration pretending to be evidence. Pretty lines can still hide a truncated axis. Before you share it, look for the numbers along the edge." }], prompt: "Which choice best describes the function of the second sentence?", choices: { A: "It names a common trick that makes the first sentence’s warning concrete", B: "It teaches how to draw circles", C: "It praises all infographics", D: "It provides election results" }, answer: "A", explain: { correct: "A truncated axis is a specific way pretty lines mislead, supporting the opening claim.", wrong: { B: "No drawing lesson appears.", C: "The stance is skeptical.", D: "No results appear." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "State the myth. Offer the archive. Then leave a remainder: what the archive cannot settle. Intellectual honesty is not only replacing false stories. It is marking the edge of the files." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "A three-step method, then a definition of honesty in terms of that method", B: "A packing list", C: "A sports recap", D: "A medical diagnosis" }, answer: "A", explain: { correct: "Myth, archive, remainder, then honesty as marking the files’ edge.", wrong: { B: "No travel list appears.", C: "No game appears.", D: "No clinic scene appears." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Congestion pricing works because it makes drivers pay a cost they had been imposing on everyone else. Time lost in a jam is a real cost; a toll merely makes it visible at the entrance ramp." }, { label: "Text 2", body: "A toll that is visible only to people with bank accounts and transponders is not a perfectly fair mirror of social cost. Workers on night shifts, and drivers without easy digital payment, need a nonpunitive way through or around the zone." }], prompt: "Both authors would most likely agree that", choices: { A: "traffic delay has social costs worth taking seriously", B: "all tolls should be abolished tomorrow", C: "night-shift workers do not exist", D: "ramps cannot be priced" }, answer: "A", explain: { correct: "Text 1 treats jam time as a real cost; Text 2 still talks about social cost, then worries about who pays how.", wrong: { B: "Text 1 defends pricing; Text 2 wants fairer design, not abolition of the idea.", C: "Text 2 explicitly mentions those workers.", D: "Text 1 locates the toll at the ramp." } } }
  ]
},
{
  day: 15, date: "2026-10-03",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The director ______ the scene until the actors stopped performing emotion and started occupying the room." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "rehearsed", B: "deleted from history", C: "scored for orchestra only", D: "sold" }, answer: "A", explain: { correct: "Rehearsed means practiced; repeating until behavior changed is rehearsal.", wrong: { B: "The scene is being worked, not erased from history.", C: "Orchestra scoring is not implied.", D: "Sold is commercial." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Because rainfall was ______ that spring, the reservoir stayed below the line that triggers water restrictions." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "meager", B: "torrential", C: "decorative", D: "theoretical" }, answer: "A", explain: { correct: "Meager means scant; little rain keeps a reservoir low.", wrong: { B: "Torrential rain would fill the reservoir.", C: "Decorative is unrelated.", D: "Theoretical rain is not measured against a trigger line." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The biography is ______ toward its subject, noting cruelty as well as talent, and refusing the souvenir-shop version of a life." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "clear-eyed", B: "worshipful", C: "silent", D: "alphabetical" }, answer: "A", explain: { correct: "Clear-eyed means unsentimental and accurate; noting cruelty and talent fits.", wrong: { B: "Worshipful would skip cruelty.", C: "The book notes things, so not silent.", D: "Alphabetical is organization, not stance." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Lawyers tried to ______ the emails as routine banter, but the timestamps showed they were sent during the vote." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "characterize", B: "shred legally", C: "compose", D: "translate into Latin" }, answer: "A", explain: { correct: "Characterize means describe as; calling emails banter is a characterization the timestamps challenge.", wrong: { B: "They are spinning meaning, not necessarily shredding.", C: "Compose would mean writing the emails, not labeling them.", D: "Latin is irrelevant." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The two theories are ______: if one is true, the predicted particles cannot exist as the other requires." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "mutually exclusive", B: "identical", C: "untested by definition", D: "decorative" }, answer: "A", explain: { correct: "Mutually exclusive means both cannot be true; incompatible particle predictions fit.", wrong: { B: "Identical theories would share predictions.", C: "The sentence is about conflict, not untestability.", D: "Decorative is irrelevant." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "He spoke with ______, naming dates and clause numbers instead of offering a mood." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "specificity", B: "vagueness", C: "melody", D: "indifference to facts" }, answer: "A", explain: { correct: "Specificity is precision; dates and clause numbers are specific.", wrong: { B: "Vagueness is the opposite of named clauses.", C: "Melody is musical.", D: "He is using facts, not ignoring them." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A “natural flavor” on a label is a legal category, not a walk in a meadow. It can still be processed, concentrated, and shipped. Readers who treat the word as a landscape are reading marketing, not agriculture." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To separate a regulatory phrase from a pastoral image", B: "To teach farming in meadows", C: "To ban all flavorings", D: "To review a restaurant" }, answer: "A", explain: { correct: "Legal category versus meadow, then marketing versus agriculture.", wrong: { B: "No farming lesson appears.", C: "No ban is issued.", D: "No restaurant is reviewed." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "Notice how often a profile of a CEO begins in a childhood garage. The garage is doing work: it turns capital, schools, and luck into a fable of solitude. Once you see the garage, you can start asking what else was in the driveway." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It invites skepticism about the garage as a complete origin story", B: "It gives driving directions", C: "It lists stock prices", D: "It denies that childhoods happen" }, answer: "A", explain: { correct: "Asking what else was in the driveway pushes past the solitude fable.", wrong: { B: "Driveway is metaphorical.", C: "No prices appear.", D: "Childhood is assumed; the fable is the target." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Collect outliers. Then decide whether they are errors, exceptions, or the actual phenomenon you should have been studying. A point that ruins a clean line might be the reason you ran the study." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "An instruction, a branching judgment, then a revaluation of messy data", B: "A packing checklist", C: "A sonnet", D: "A bus schedule" }, answer: "A", explain: { correct: "Collect, classify (error/exception/phenomenon), then the claim that the ruined line may be the point.", wrong: { B: "No travel list appears.", C: "Not a poem form.", D: "No times appear." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "National service should be mandatory at eighteen. Shared work across class lines builds a civic identity that elective volunteering never reaches, because elective programs recruit the already willing." }, { label: "Text 2", body: "Compulsion can build resentment as easily as solidarity. A well-paid voluntary corps, targeted at both elite campuses and towns with few opportunities, can mix classes without turning citizenship into a sentence." }], prompt: "Which choice best describes the difference between the texts?", choices: { A: "Text 1 treats mandates as necessary for mixing classes; Text 2 thinks paid volunteering can mix classes without compulsion", B: "Text 1 opposes all civic work; Text 2 requires military drafts only", C: "Both reject any mixing of social classes", D: "Text 2 claims eighteen-year-olds do not exist" }, answer: "A", explain: { correct: "Text 1 says only mandates mix classes; Text 2 proposes paid voluntary mixing instead.", wrong: { B: "Text 1 wants service, not opposition to civic work.", C: "Both want mixing, by different means.", D: "Text 2 discusses those citizens as real." } } }
  ]
},
{
  day: 16, date: "2026-10-04",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The island’s roads were ______ after the storm, so relief trucks waited at the ferry until crews cut through fallen trees." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "impassable", B: "scenic", C: "new", D: "theoretical" }, answer: "A", explain: { correct: "Impassable means cannot be traveled; trucks waiting for tree-cutting fits.", wrong: { B: "Scenic is about views.", C: "Newness is not why trucks wait.", D: "Theoretical roads are not blocked by trees." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Reviewers praised the essay’s ______: it covered a century without sounding like a list of dates." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "sweep", B: "narrowness", C: "hostility", D: "anonymity" }, answer: "A", explain: { correct: "Sweep means wide range; a century covered with shape, not a date list, fits.", wrong: { B: "Narrowness contradicts a century’s span.", C: "Hostility is tone.", D: "Anonymity is about names." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The mayor’s apology ______ the victims by using the passive voice—“mistakes were made”—and naming no office that made them." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "failed", B: "honored fully", C: "paid", D: "photographed" }, answer: "A", explain: { correct: "Failed the victims means did not do right by them; nameless passive voice is an empty apology.", wrong: { B: "Honored fully contradicts the criticism of the passive voice.", C: "Paid is financial.", D: "Photographed is irrelevant." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Because the two clocks were ______ by seven minutes, the explosion’s origin looked like two events until someone aligned the logs." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "offset", B: "identical", C: "melodic", D: "unplugged from science" }, answer: "A", explain: { correct: "Offset means out of alignment; a seven-minute gap creating a false double event fits.", wrong: { B: "Identical clocks would not create a seven-minute split.", C: "Melodic is musical.", D: "The logs are scientific records being aligned." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The poet’s images are ______ rather than ornamental; each one returns later as a plot fact." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "functional", B: "gratuitous", C: "illegible", D: "borrowed from ads only" }, answer: "A", explain: { correct: "Functional means doing work; images that return as plot facts are working, not extra decoration.", wrong: { B: "Gratuitous means unneeded, unlike returning plot facts.", C: "Illegible concerns reading the words.", D: "Ads are not mentioned." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Scientists ______ the sample to a second lab to see whether the odd reading would replicate." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "sent", B: "destroyed", C: "sang", D: "classified as art" }, answer: "A", explain: { correct: "Sent to a second lab is how you check replication of an odd reading.", wrong: { B: "Destroying the sample would block replication.", C: "Sang is unrelated.", D: "Art classification is irrelevant." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "“Average household income” can hide a town with two fortunes and a hundred strained budgets. A median, or a look at the tenth percentile, would tell a different civic story. The word “average” is doing political work when it is treated as a portrait." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To warn that averages can mask inequality and should not pass as a full portrait", B: "To teach long division", C: "To celebrate all fortunes equally", D: "To deny that incomes can be measured" }, answer: "A", explain: { correct: "Two fortunes versus strained budgets, plus median/tenth percentile, target the average-as-portrait habit.", wrong: { B: "No algorithm is taught.", C: "The point is hidden strain, not celebration.", D: "Measurement is assumed; interpretation is the issue." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "Read the dissenting opinion. Majority opinions tell you who won. Dissents sometimes tell you which fight is not over, because they write for a future court." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It explains a distinctive purpose dissents can serve", B: "It lists justices’ birthdays", C: "It argues that majority opinions should be shredded", D: "It describes courtroom architecture" }, answer: "A", explain: { correct: "Writing for a future court is the extra job dissents may do.", wrong: { B: "No birthdays appear.", C: "Majority opinions are still said to tell who won.", D: "Buildings are not discussed." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Start with a cheap sensor. Log a month. Then decide whether a better instrument is worth the grant. Many “we need more data” speeches skip the month with the cheap sensor." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "A stepwise practical method, then a criticism of skipping the first step", B: "A symphony program", C: "A wedding invitation", D: "A shipping label" }, answer: "A", explain: { correct: "Cheap sensor, log, then decide; last sentence scolds skipping that month.", wrong: { B: "Not music.", C: "Not a wedding.", D: "Not logistics paperwork." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Digitizing every local newspaper is urgent. Paper burns, floods, and turns brittle. Access arguments can wait until the pages exist as files." }, { label: "Text 2", body: "A file that no one can find is only a slightly safer form of loss. Digitization projects that skip metadata, rights, and a public catalog recreate the locked basement—on a server." }], prompt: "Text 2 would most likely respond to Text 1 by", choices: { A: "agreeing that paper is vulnerable but insisting that findability is part of saving the pages", B: "denying that paper ever deteriorates", C: "arguing that newspapers should never be read", D: "claiming servers cannot store files" }, answer: "A", explain: { correct: "Text 2 grants a safer form (so paper risk is real) then says missing catalogs recreate the locked basement.", wrong: { B: "Text 2 does not deny paper’s vulnerability.", C: "Both want access in some form.", D: "Text 2 assumes server storage, then criticizes its design." } } }
  ]
},
{
  day: 17, date: "2026-10-05",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The truce talks were ______ by a border incident that neither side would call an accident." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "derailed", B: "accelerated smoothly", C: "ignored by physics", D: "rhymed" }, answer: "A", explain: { correct: "Derailed means thrown off course; an incident neither side treats as accidental would stall talks.", wrong: { B: "Accelerated smoothly contradicts a stalling incident.", C: "Physics is irrelevant.", D: "Rhymed is poetic." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Her prose is ______: clauses nest inside clauses until a reader forgets the original subject." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "convoluted", B: "plainspoken", C: "illustrated", D: "brief" }, answer: "A", explain: { correct: "Convoluted means overly intricate; nested clauses that bury the subject fit.", wrong: { B: "Plainspoken is the opposite.", C: "Illustrated concerns images.", D: "Brief writing would not nest until memory fails." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "Conservationists tried to ______ public support by posting daily photos of the nesting pair, not by issuing a technical brief." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "rally", B: "suppress", C: "tax", D: "translate into code" }, answer: "A", explain: { correct: "Rally means gather or mobilize; daily photos to build support fit.", wrong: { B: "Suppress support is the opposite aim.", C: "Tax is fiscal.", D: "Code is irrelevant." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "The two maps were ______ at the county line, so a road that existed on one vanished on the other." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "inconsistent", B: "identical", C: "waterproof", D: "unsigned only" }, answer: "A", explain: { correct: "Inconsistent means not in agreement; a road appearing then vanishing at the line fits.", wrong: { B: "Identical maps would match at the line.", C: "Waterproof is material.", D: "Signatures are not the issue." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "He offered a ______ of the theory, stripping the math but keeping the claim that time of day changes the result." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "digest", B: "refutation", C: "melody", D: "lawsuit" }, answer: "A", explain: { correct: "A digest is a condensed version; stripping math while keeping the core claim fits.", wrong: { B: "A refutation would attack the claim, not keep it.", C: "Melody is musical.", D: "Lawsuit is legal." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Shopkeepers grew ______ as theft rose and police response times stretched past an hour." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "exasperated", B: "soothed", C: "unaware", D: "festive" }, answer: "A", explain: { correct: "Exasperated means intensely irritated; rising theft and slow response fit.", wrong: { B: "Soothed is the opposite.", C: "They are reacting to known conditions.", D: "Festive does not match the problem." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A restoration that makes a painting look “new” can erase the history of its damage. Cracks are not only flaws. They are a record of rooms, weather, and earlier hands. Cleaning is a choice about which past to keep visible." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To argue that cleaning decisions are historical choices, not purely technical ones", B: "To sell varnish", C: "To deny that paintings crack", D: "To narrate a museum heist" }, answer: "A", explain: { correct: "Cracks as record and “which past to keep visible” make cleaning interpretive.", wrong: { B: "No product is sold.", C: "Cracks are treated as real records.", D: "No heist appears." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "If a study’s abstract says “proves,” read the limitations paragraph. Proof is a rare guest in empirical work. Hedging is not weakness; it is the method talking." }], prompt: "Which choice best describes the function of the second sentence?", choices: { A: "It explains why the advice in the first sentence is needed", B: "It provides a formula", C: "It lists journals", D: "It praises all abstracts" }, answer: "A", explain: { correct: "If proof is rare, then “proves” in an abstract is a reason to check limitations.", wrong: { B: "No formula appears.", C: "No journal list appears.", D: "Abstracts that say “proves” are treated with caution." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Name the river. Then name the dam. Then name the towns that no longer flood and the fish that no longer spawn. Infrastructure always has a second ledger." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "A sequence of namings that builds to a claim about hidden costs and benefits", B: "A fishing-license application", C: "A joke with a punch line about dentists", D: "A product warranty" }, answer: "A", explain: { correct: "River, dam, towns, fish, then “second ledger.”", wrong: { B: "Not a form.", C: "Not a dentist joke.", D: "Not a warranty." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Standardized patients in medical training beat textbooks for teaching bedside manner. A scripted encounter still forces eye contact, silence, and the habit of asking one more question." }, { label: "Text 2", body: "Scripted patients teach manners as choreography. They underteach the messy visit in which the story changes twice and the clock wins. Pair the actor with an unscripted clinic afternoon, or the lesson ossifies." }], prompt: "The author of Text 2 would most likely", choices: { A: "treat Text 1’s method as useful but incomplete without unscripted practice", B: "reject all patient contact in training", C: "claim textbooks beat all encounters", D: "deny that clocks exist in clinics" }, answer: "A", explain: { correct: "Text 2 does not ban actors; it says to pair them with messy clinic time so the lesson does not harden.", wrong: { B: "Text 2 still uses encounters.", C: "Text 1 prefers patients to textbooks; Text 2 does not reverse that into textbooks winning.", D: "Text 2 treats the clock as a real pressure." } } }
  ]
},
{
  day: 18, date: "2026-10-06",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The evidence was ______ at best: one blurry photo and a neighbor who “thought” she heard a van." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "thin", B: "overwhelming", C: "color-coded", D: "notarized" }, answer: "A", explain: { correct: "Thin evidence is weak; a blurry photo and an uncertain sound fit.", wrong: { B: "Overwhelming would be strong evidence.", C: "Color-coded is format.", D: "Notarized is a legal stamp, not strength." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Rather than ______ the old theater, the city retrofitted it, keeping the marquee and replacing the wiring." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "raze", B: "restore only the popcorn", C: "ignore", D: "rename nightly" }, answer: "A", explain: { correct: "Raze means demolish; retrofitting instead of tearing down fits “rather than.”", wrong: { B: "Popcorn is not the alternative described.", C: "They did work on the theater, so they did not ignore it.", D: "Renaming nightly is not the contrast with retrofitting." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The senator’s ______ to the question—she answered a different one—was noticed by every reporter in the room." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "deflection", B: "directness", C: "silence", D: "laughter only" }, answer: "A", explain: { correct: "Deflection means turning aside; answering a different question is classic deflection.", wrong: { B: "Directness would answer the question asked.", C: "She did speak, so not silence.", D: "Laughter is not specified." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Wildlife cameras showed that the cats were more ______ than the daytime surveys had suggested, moving mostly after midnight." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "nocturnal", B: "extinct", C: "tame", D: "flightless" }, answer: "A", explain: { correct: "Nocturnal means active at night; midnight movement fits.", wrong: { B: "Extinct animals would not appear on cameras.", C: "Tame is about domestication.", D: "Flightless concerns wings, not schedule." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The introduction ______ what the chapters actually do, promising a global history and then delivering five case studies from one coast." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "overstates", B: "understates modestly", C: "omits all verbs from", D: "translates" }, answer: "A", explain: { correct: "Overstates means claims too much; global promise versus one-coast cases fits.", wrong: { B: "Understates would promise less than the chapters give.", C: "Verbs are not the issue.", D: "Translate is language." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Nurses asked the hospital to ______ the alarm threshold so that routine beeps would stop drowning out true emergencies." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "recalibrate", B: "ignore forever", C: "sell", D: "paint" }, answer: "A", explain: { correct: "Recalibrate means reset a measurement or threshold; reducing false beeps fits.", wrong: { B: "They want a better threshold, not no alarms.", C: "Sell is commercial.", D: "Paint is unrelated." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A monument’s plaque is a first draft of public memory. It is also a piece of metal someone had to approve. Reading the plaque and then asking who paid for it are not two hobbies. They are one method." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To treat plaques as both text and political objects that should be read together", B: "To explain metallurgy", C: "To ban all plaques", D: "To give walking-tour jokes" }, answer: "A", explain: { correct: "First draft plus who paid, then “one method,” fuses reading and funding questions.", wrong: { B: "Metal is mentioned, not taught as science.", C: "No ban appears.", D: "Tone is methodological, not comic tour-guide." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "Do not start with the theory. Start with the anomaly the theory cannot digest. If you still need the theory after that, you have earned it." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It states the condition under which theory becomes justified", B: "It defines a chemical anomaly", C: "It lists famous theorists", D: "It cancels the first sentence" }, answer: "A", explain: { correct: "“If you still need the theory after that, you have earned it” is the condition.", wrong: { B: "No chemistry definition appears.", C: "No list appears.", D: "The last sentence completes, rather than cancels, the advice." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "A flood map from 1990 and a flood map from this year will not match. That mismatch is the finding. Climate is not only a future tense; it is a difference between two official pictures." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "A comparison is proposed, named as the result, then generalized", B: "A boat-safety checklist", C: "A restaurant review", D: "A crossword clue" }, answer: "A", explain: { correct: "Two maps, mismatch as finding, then climate as difference between pictures.", wrong: { B: "Not a checklist.", C: "Not food.", D: "Not a puzzle clue." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Ban phones from lecture halls. Attention is a public good in a shared room, and one screen in a dark row becomes ten screens." }, { label: "Text 2", body: "A ban that ignores students who record audio because of disability accommodations will be struck, and should be. Design a default off, with a documented exception process, rather than a performance of purity." }], prompt: "Based on the texts, both authors are concerned with", choices: { A: "how phone use in class should be governed", B: "how to manufacture phones", C: "whether lectures should be replaced by sports", D: "campus dining hours" }, answer: "A", explain: { correct: "Text 1 wants a ban; Text 2 wants default-off plus accommodations. Both are about classroom phone rules.", wrong: { B: "Neither discusses manufacturing.", C: "Lectures remain the setting.", D: "Dining is not mentioned." } } }
  ]
},
{
  day: 19, date: "2026-10-07",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The committee’s language was deliberately ______ so that later boards could tighten or loosen the rule without a new statute." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "elastic", B: "carved in stone", C: "rhymed", D: "untranslatable" }, answer: "A", explain: { correct: "Elastic means able to stretch; wording that later boards can tighten or loosen fits.", wrong: { B: "Carved in stone would block later adjustment.", C: "Rhymed is poetic.", D: "Untranslatable concerns language barriers." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Fossils were so ______ in the cliff that students could not take a step without pointing at a shell." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "abundant", B: "rare", C: "imaginary", D: "recently painted" }, answer: "A", explain: { correct: "Abundant means plentiful; shells at every step fit.", wrong: { B: "Rare contradicts every-step pointing.", C: "Imaginary fossils would not be pointed at as shells.", D: "Painted is not implied." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The memoirist does not ______ her younger self; she quotes the cruel diary and then refuses to sand it down." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "exonerate", B: "interview", C: "employ", D: "photograph" }, answer: "A", explain: { correct: "Exonerate means clear of blame; quoting a cruel diary without sanding it down is refusal to clear that self.", wrong: { B: "Interview is not the moral action described.", C: "Employ is work.", D: "Photograph is irrelevant." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Traffic engineers ______ the intersection after three similar crashes, adding a leading pedestrian interval." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "redesigned", B: "ignored", C: "named", D: "filmed for sport" }, answer: "A", explain: { correct: "Redesigned means planned again; adding a pedestrian interval after crashes is a redesign.", wrong: { B: "They added a feature, so they did not ignore it.", C: "Named is not the intervention.", D: "Sport filming is irrelevant." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "His analogy was ______: comparing a city budget to a household budget hid debts that no household can print." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "misleading", B: "perfect", C: "musical", D: "unspoken" }, answer: "A", explain: { correct: "Misleading means it sends you wrong; hiding printable-debt differences is a bad analogy.", wrong: { B: "Perfect would not hide a key difference.", C: "Musical is irrelevant.", D: "The analogy was offered, so not unspoken." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "The species had been labeled ______ until a camera trap in 2019 recorded a pair with young." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "extinct", B: "domestic", C: "aquatic only in labs", D: "famous" }, answer: "A", explain: { correct: "Extinct means gone; a later camera-trap family overturns that label.", wrong: { B: "Domestic means tamed.", C: "Labs and aquatic limits are not in the sentence.", D: "Famous is about celebrity." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A trigger warning is not a substitute for a syllabus. It can be a courtesy at the door. The course still has to do the reading, the argument, and the sitting with difficulty after you walk in." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To limit what trigger warnings can accomplish relative to actual coursework", B: "To ban all warnings", C: "To replace courses with warnings", D: "To review a novel" }, answer: "A", explain: { correct: "Not a substitute, courtesy at the door, then the course’s remaining work.", wrong: { B: "Courtesy is allowed; a total ban is not argued.", C: "The opposite: the course still must happen.", D: "No novel is reviewed." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "Watch the credits to the end. The “best boy” and the caterer are not trivia. They are how a supposedly solitary artwork actually got made before dinner." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It interprets credits as evidence of collective labor", B: "It lists recipes", C: "It attacks catering", D: "It explains camera sensors" }, answer: "A", explain: { correct: "Best boy and caterer as how the work got made before dinner = collective labor.", wrong: { B: "Dinner is a time marker, not a cookbook.", C: "Caterer is included as labor, not attacked.", D: "No sensor science appears." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Pose the question in one sentence. Dump the method in two. Then spend your remaining space on what surprised you. Readers can smell a paper that hid the surprise in order to look inevitable." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "Advice on allocating space in a paper, with a warning about false inevitability", B: "A lab safety poster", C: "A poem about smell", D: "A shipping invoice" }, answer: "A", explain: { correct: "Question, method, surprise, then the smell-test warning.", wrong: { B: "Not safety rules.", C: "Smell is metaphorical.", D: "Not an invoice." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Urban tree planting should prioritize streets with the highest surface temperatures, even if those plantings are more expensive per tree because of concrete cuts." }, { label: "Text 2", body: "Heat maps are a start. Survival maps are better. A sapling that dies in compacted soil cools no one. Spend on soil volume and watering in already-hot blocks, not on a body count of trees that will be stumps in three years." }], prompt: "Text 2 would most likely modify Text 1’s priority by", choices: { A: "keeping hot streets in view but insisting on conditions that let trees live", B: "planting only in already-cool parks", C: "banning all concrete cuts", D: "ignoring temperature entirely" }, answer: "A", explain: { correct: "Text 2 says spend on soil and water in already-hot blocks—so heat still matters—while rejecting a mere count of doomed saplings.", wrong: { B: "Hot blocks remain the location.", C: "Text 1’s concrete cuts are not banned; survival costs are added.", D: "Heat maps are “a start,” not discarded." } } }
  ]
},
{
  day: 20, date: "2026-10-08",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The archive was ______ to journalists until a court order forced the agency to release the boxes." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "inaccessible", B: "catalogued on every homepage", C: "destroyed after release", D: "written in verse" }, answer: "A", explain: { correct: "Inaccessible means not available; a court order forcing release implies prior lockout.", wrong: { B: "Homepage cataloguing would be access, not a lockout.", C: "The boxes are released, not said to be destroyed after.", D: "Verse is irrelevant." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Her argument ______ when she moved from measured pollution data to a claim about voters’ secret motives." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "overreached", B: "tightened", C: "rhymed", D: "ended before it began" }, answer: "A", explain: { correct: "Overreached means went beyond what could be supported; secret motives outrun pollution data.", wrong: { B: "Tightened would mean more careful, not a leap to motives.", C: "Rhymed is poetic.", D: "The argument did move, so it did not end before beginning." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The truce was ______ by small gifts of medicine, which did not end the war but made the next conversation possible." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "lubricated", B: "prevented", C: "ignored", D: "translated into opera" }, answer: "A", explain: { correct: "Lubricated means made to run more smoothly; medicine gifts enabling talk fit the metaphor.", wrong: { B: "Prevented would stop the truce; gifts help it.", C: "The gifts are doing work, not being ignored.", D: "Opera is irrelevant." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Because the sample was ______—twelve people from one clinic—the authors warned against national conclusions." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "narrow", B: "representative of every region", C: "imaginary", D: "infinite" }, answer: "A", explain: { correct: "Narrow means limited in range; twelve people from one clinic fits, hence no national leap.", wrong: { B: "Representative nationally would allow national conclusions.", C: "The twelve people are real in the study.", D: "Infinite contradicts twelve." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The restoration was ______: workers matched mortar to the original mix rather than using a cheaper modern blend that would have trapped moisture." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "scrupulous", B: "hasty", C: "purely decorative", D: "unfunded" }, answer: "A", explain: { correct: "Scrupulous means carefully exact; matching mortar to avoid moisture damage is careful work.", wrong: { B: "Hasty would suggest the cheap blend.", C: "Moisture control is structural, not mere decoration.", D: "Work happened, so it was funded enough to proceed." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Listeners found the lecture ______ until the speaker replaced jargon with a single worked example." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "opaque", B: "crystal-clear from the first word", C: "silent", D: "musical" }, answer: "A", explain: { correct: "Opaque means hard to see through; jargon that clears after an example fits.", wrong: { B: "Crystal-clear from the start contradicts the need for an example.", C: "There was a lecture, so not silent.", D: "Musical is unrelated." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A “smart” city dashboard that tracks potholes but not eviction filings is not a complete picture of urban health. What gets a widget gets a crew. What does not get a widget waits." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To criticize incomplete metrics that steer attention and resources", B: "To explain how to fill potholes", C: "To praise all dashboards", D: "To narrate an eviction from one family’s view only as memoir" }, answer: "A", explain: { correct: "Potholes versus evictions, then widget-equals-crew, is a critique of what dashboards omit.", wrong: { B: "Potholes are an example of what is tracked, not a how-to.", C: "The stance is critical.", D: "No single-family memoir is told." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "The epigraph is a rented authority. Sometimes it earns its keep by framing the chapter. Sometimes it is name-dropping in italics." }], prompt: "Which choice best describes the function of the last two sentences?", choices: { A: "They split epigraphs into useful frames versus empty prestige", B: "They teach italic formatting in full", C: "They list banned authors", D: "They summarize the novel’s plot" }, answer: "A", explain: { correct: "Framing versus name-dropping is a two-way evaluation after “rented authority.”", wrong: { B: "Italics are mentioned, not taught as a manual.", C: "No ban list appears.", D: "No plot is summarized." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Measure the baseline. Intervene. Measure again. If you skip the first measurement, every later number is a rumor about improvement." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "A three-step experimental logic, then the cost of skipping step one", B: "A travel diary", C: "A recipe for rumor mills as businesses", D: "A seating chart" }, answer: "A", explain: { correct: "Baseline, intervene, remeasure, then skip-baseline equals rumor.", wrong: { B: "Not travel.", C: "Rumor is a metaphor for bad inference.", D: "Not seating." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Community solar should sit on warehouses, not on farmland. Food-producing acres are already scarce, and rooftops are otherwise wasted plane." }, { label: "Text 2", body: "Warehouse roofs are ideal until you count the warehouses that cannot bear the load or that sit in shade. Dual-use arrays over certain crops can keep land in production and still add power. The right site is an engineering answer, not a slogan about roofs versus fields." }], prompt: "Which choice best describes the relationship between the texts?", choices: { A: "Text 2 treats Text 1’s roof preference as too sweeping and offers mixed siting, including some farmland dual use", B: "Text 2 agrees that all farmland must host panels and no roofs should", C: "Text 1 and Text 2 discuss only offshore wind", D: "Text 2 denies that warehouses exist" }, answer: "A", explain: { correct: "Text 2 lists roof limits and allows dual-use over crops, calling slogans insufficient.", wrong: { B: "That reverses both authors.", C: "Both discuss solar siting on land/roofs.", D: "Text 2 discusses warehouse load and shade as real." } } }
  ]
}
);
