window.SAT_DAYS = window.SAT_DAYS || [];
window.SAT_DAYS.push(
{
  day: 41, date: "2026-10-29",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The ferry schedule was ______ in winter, with two of five daily runs canceled whenever winds topped thirty knots." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "unreliable", B: "clockwork", C: "decorative", D: "theoretical" }, answer: "A", explain: { correct: "Unreliable means not dependable; frequent wind cancellations fit.", wrong: { B: "Clockwork would mean it always ran.", C: "Decorative is unrelated.", D: "Canceled runs are real, not theoretical." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Historians ______ a second ledger that listed payments the official minutes had omitted." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "unearthed", B: "composed as fiction", C: "sang", D: "ignored on purpose then" }, answer: "A", explain: { correct: "Unearthed means found; a hidden ledger of omitted payments fits discovery.", wrong: { B: "They treat it as a record, not as composed fiction.", C: "Sang is unrelated.", D: "Finding it is the opposite of ignoring it then." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The director’s cut is more ______ than the studio version, restoring silences the producers had filled with music." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "austere", B: "crowded", C: "silent in the sense of having no film", D: "rhymed" }, answer: "A", explain: { correct: "Austere means stripped-down; restored silences versus filled-in music fit.", wrong: { B: "Crowded would add more, not restore silence.", C: "There is still a film.", D: "Rhymed is verse." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Prairie dogs ______ soil, turning packed ground into a mosaic of mounds that change how water soaks in." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "aerate", B: "pave", C: "ignore", D: "translate" }, answer: "A", explain: { correct: "Aerate means add air spaces; mounds changing infiltration fit digging animals.", wrong: { B: "Pave would seal soil.", C: "They are altering soil, not ignoring it.", D: "Translate is language." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The analogy ______ a city as a family, which hid debts no family can issue as bonds." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "treated", B: "refused to describe", C: "set to music", D: "photographed" }, answer: "A", explain: { correct: "Treated as means figured as; city-as-family hiding bond-issuing power fits.", wrong: { B: "The analogy did describe the city that way.", C: "Music is unrelated.", D: "Photographed is irrelevant." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Because the two instruments ______, the team published a range rather than a single temperature." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "disagreed", B: "matched to the thousandth", C: "melted", D: "sang" }, answer: "A", explain: { correct: "Disagreed means they did not match; publishing a range is the honest response.", wrong: { B: "Perfect matching would allow a single number.", C: "Melted is not indicated.", D: "Sang is unrelated." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A “historic” designation that protects a facade and not the tenants is a postcard policy. History is also who can still afford the rent behind the brick." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To argue that preservation should include who remains in the building", B: "To sell postcards", C: "To deny that brick exists", D: "To teach masonry" }, answer: "A", explain: { correct: "Facade versus tenants, postcard policy, rent behind brick.", wrong: { B: "Postcard is a metaphor for surface.", C: "Brick is assumed.", D: "No masonry lesson appears." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "A methods section that cannot be followed is a spell, not a recipe. Science shares the kitchen." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It states the collaborative norm that unfollowable methods violate", B: "It lists recipes", C: "It praises spells", D: "It describes a kitchen remodel" }, answer: "A", explain: { correct: "Science shares the kitchen means methods should be copyable, unlike a spell.", wrong: { B: "Recipe is a metaphor.", C: "Spell is the failure mode.", D: "Kitchen is metaphorical." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Count the promises. Count the budget lines. Count the staff. A plan is the smallest of those three numbers." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "Three counts that redefine a plan as the binding constraint", B: "A staff party invitation", C: "A promise as a wedding vow only", D: "A budget as a novel" }, answer: "A", explain: { correct: "Promises, lines, staff, then the plan equals the smallest.", wrong: { B: "Not a party.", C: "Promises are policy promises.", D: "Not a novel." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Congestion pricing should fund transit first, not road widening. Charging drivers to pay for more asphalt recreates the jam." }, { label: "Text 2", body: "Transit first is right on paper. If the bus that the toll funds still comes every forty minutes, drivers will pay and stay in cars. Sequence the bus improvement so that it is visible before the gantry turns on." }], prompt: "Text 2 would most likely", choices: { A: "agree that tolls should support transit but insist the service exist before the charge bites", B: "demand that all tolls fund extra lanes", C: "deny that buses exist", D: "claim asphalt cannot be funded" }, answer: "A", explain: { correct: "Text 2 says transit first is right, then requires visible bus improvement before gantries.", wrong: { B: "That is what Text 1 rejects; Text 2 does not reverse to widening.", C: "Buses are the solution Text 2 wants visible.", D: "Not the issue." } } }
  ]
},
{
  day: 42, date: "2026-10-30",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The island clinic’s generator was ______, kicking on in tests and failing on the first real outage." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "untrustworthy", B: "flawless", C: "decorative", D: "theoretical" }, answer: "A", explain: { correct: "Untrustworthy means not reliable; passing tests and failing when needed fits.", wrong: { B: "Flawless would work in the outage.", C: "Decorative is unrelated.", D: "A real outage happened." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Editors ______ three similar anecdotes into one, which tightened the chapter without losing the point." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "collapsed", B: "expanded", C: "sang", D: "ignored" }, answer: "A", explain: { correct: "Collapsed into one means combined; tightening without losing the point fits.", wrong: { B: "Expanded would not tighten.", C: "Sang is unrelated.", D: "They edited, so they did not ignore the anecdotes." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The biography is ______ toward myth, pausing to note when a famous story first appears in print—often decades after the event." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "skeptical", B: "credulous", C: "silent", D: "rhymed" }, answer: "A", explain: { correct: "Skeptical toward myth means it questions origin stories; dating first print decades later fits.", wrong: { B: "Credulous would repeat the myth untested.", C: "Noting print dates is not silence.", D: "Rhymed is form." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Kelp forests ______ urchins when otters are present, because otters eat the urchins that would otherwise mow the kelp." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "outlast", B: "vanish because of", C: "ignore", D: "translate" }, answer: "A", explain: { correct: "Outlast means persist longer than; otters eating urchins lets kelp persist against urchin grazing.", wrong: { B: "Vanish because of urchins is the no-otter case.", C: "The food web is causal, not ignoring.", D: "Translate is language." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The slogan ______ a complex housing bill into four words that left out the funding trigger." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "compressed", B: "expanded faithfully", C: "set to an opera", D: "notarized" }, answer: "A", explain: { correct: "Compressed means squeezed down; four words omitting the trigger is over-compression.", wrong: { B: "Faithful expansion would keep the trigger.", C: "Opera is unrelated.", D: "Notarized is a stamp." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Two field sites ______ the same drought signal in tree rings, which made a local pest outbreak a weaker explanation." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "showed", B: "hid", C: "composed", D: "sold" }, answer: "A", explain: { correct: "Showed the same signal in two places weakens a purely local pest story.", wrong: { B: "Hiding would not support a regional drought.", C: "Composed suggests fabrication.", D: "Sold is commercial." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A “paperless” courtroom still prints the exhibit that matters. Digital is a default, not a disappearance. Ask which pile still exists when the system goes down." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To puncture paperless claims by pointing to remaining physical piles and downtime", B: "To sell printers", C: "To deny that courts use files", D: "To teach software coding" }, answer: "A", explain: { correct: "Still prints, default not disappearance, pile when the system goes down.", wrong: { B: "Printing is evidence, not an ad.", C: "Files are assumed.", D: "No coding lesson appears." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "An epigraph from a famous dead writer can frame a chapter. It can also be a rented gravitas sticker. Steal well, or don’t." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It issues a terse rule after naming two uses of epigraphs", B: "It lists dead writers", C: "It teaches sticker design", D: "It bans all quotation" }, answer: "A", explain: { correct: "Steal well, or don’t is the rule after frame versus rented gravitas.", wrong: { B: "No list appears.", C: "Sticker is metaphorical.", D: "Stealing well allows quotation." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "List the claim. List the sample. List who was left out. Generalization is a trespass onto the left-out." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "Three lists that lead to a warning about overgeneralizing", B: "A trespass as a criminal-law treatise", C: "A sample as a free supermarket bite", D: "A claim as an insurance form" }, answer: "A", explain: { correct: "Claim, sample, left-out, then trespass onto the left-out.", wrong: { B: "Trespass is metaphorical.", C: "Sample means research sample.", D: "Not insurance." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Remote work should be a default right, not a perk. Offices exist to serve work, not to fill furniture contracts." }, { label: "Text 2", body: "A default right that ignores labs, clinics, and assembly lines writes policy for one class of keyboard jobs. Rights can be strong in jobs where presence is optional. Pretending presence is always optional is how a good idea becomes a slogan that factory workers correctly ignore." }], prompt: "The author of Text 2 would most likely say Text 1", choices: { A: "overgeneralizes from jobs in which being on-site is optional", B: "is correct about assembly lines needing remote defaults", C: "should fill more furniture contracts", D: "denies that offices exist" }, answer: "A", explain: { correct: "Text 2 names labs, clinics, and lines as jobs where presence is not optional, so a universal default overreaches.", wrong: { B: "Text 2 says those jobs are exactly where remote default fails.", C: "Furniture contracts are Text 1’s jab; Text 2 does not defend them.", D: "Both discuss offices as real." } } }
  ]
},
{
  day: 43, date: "2026-10-31",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The path along the bluff was ______ after the slide, and rangers closed it until engineers could test the remaining soil." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "unsafe", B: "certified", C: "theoretical", D: "decorative" }, answer: "A", explain: { correct: "Unsafe after a slide, pending tests, fits a closure.", wrong: { B: "Certified would keep it open.", C: "A real slide happened.", D: "Decorative is unrelated." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "The reporter ______ unnamed sources only after two on-the-record officials had already confirmed the core fact." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "used", B: "invented", C: "sang", D: "sold" }, answer: "A", explain: { correct: "Used unnamed sources after confirmation is a sourcing choice.", wrong: { B: "Invented would not wait on officials.", C: "Sang is unrelated.", D: "Sold is commercial." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The essay’s ______—short sentences, few metaphors—makes the accusation land without a poet’s cushion." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "plainness", B: "ornateness", C: "illegibility", D: "length" }, answer: "A", explain: { correct: "Plainness is unadorned style; short sentences and few metaphors fit.", wrong: { B: "Ornateness would add metaphors.", C: "Illegibility is about being unreadable as text.", D: "Length is not sentence style." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Beavers ______ flood peaks on the ranch by spreading water into a chain of ponds." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "lowered", B: "raised without limit", C: "ignored", D: "patented" }, answer: "A", explain: { correct: "Lowered peaks by spreading water is flood attenuation.", wrong: { B: "Raising without limit contradicts spreading to cut peaks.", C: "Beavers are changing hydrology.", D: "Patented is legal." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The comparison was ______, lining up a school lunch line with a prison cafeteria to force a moral that neither place had asked for." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "strained", B: "seamless", C: "unspoken", D: "statistical" }, answer: "A", explain: { correct: "Strained means forced beyond a good fit; an unasked-for moral from unlike lines fits.", wrong: { B: "Seamless would mean a natural fit.", C: "The comparison was made.", D: "Statistical is not the ethical issue." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Authors ______ their code after reviewers could not reproduce a figure from the paper alone." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "released", B: "destroyed", C: "rhymed", D: "hid more deeply" }, answer: "A", explain: { correct: "Released code so others can reproduce a figure is the response to failed reproduction from the paper alone.", wrong: { B: "Destroyed code would block reproduction more.", C: "Rhymed is poetic.", D: "Hiding more deeply is the opposite of helping reviewers." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A “vision zero” banner that does not change signal timing is a mural. Zero is a design target. Paint cannot meet it." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To insist that a safety slogan requires operational changes, not only banners", B: "To sell paint", C: "To deny that signals exist", D: "To teach mural technique" }, answer: "A", explain: { correct: "Banner without timing, mural, zero as design, paint cannot meet it.", wrong: { B: "Paint is the inadequate gesture.", C: "Signals are what should change.", D: "Mural is a metaphor." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "“Needless to say” tries to recruit you as someone who already agrees. Decline the recruitment. Ask for the need." }], prompt: "Which choice best describes the function of the last two sentences?", choices: { A: "They tell the reader how to resist the phrase’s pressure", B: "They define recruitment in the military", C: "They list needs", D: "They agree that nothing need be said" }, answer: "A", explain: { correct: "Decline recruitment and ask for the need is resistance to “needless to say.”", wrong: { B: "Recruitment is rhetorical.", C: "No list appears.", D: "They demand the need be stated." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Map the outage. Map the cooling center. Map who had a car. Disaster is a transportation story as much as a weather story." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "Three mappings that recast disaster as partly about movement", B: "A car advertisement", C: "A weather textbook in full", D: "A cooling as a physics derivation" }, answer: "A", explain: { correct: "Outage, center, car, then transportation as much as weather.", wrong: { B: "Car means access, not an ad.", C: "Weather is only half the story.", D: "Cooling center is a civic site." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Library ebook licenses that expire after 26 checkouts should be illegal. Public collections are not a streaming trial." }, { label: "Text 2", body: "Expiring licenses are extractive, and a ban without a funding path can shrink the catalog to whatever publishers will still sell. Pair a longer-license rule with state money, or the victory is an emptier shelf." }], prompt: "Both authors would most likely agree that", choices: { A: "current expiring ebook licenses are a bad deal for public libraries", B: "libraries should close", C: "26 is a sacred number", D: "publishers do not exist" }, answer: "A", explain: { correct: "Text 1 wants them illegal; Text 2 calls them extractive. Shared: they are bad for libraries.", wrong: { B: "Both want collections to exist.", C: "26 is the criticized limit.", D: "Text 2 discusses what publishers will sell." } } }
  ]
},
{
  day: 44, date: "2026-11-01",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The radio link went ______ at dusk, a daily fade that the island had learned to plan around." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "dead", B: "stronger than noon", C: "decorative", D: "theoretical" }, answer: "A", explain: { correct: "Went dead means it stopped working; a daily dusk fade they plan around fits.", wrong: { B: "Stronger than noon would not need planning around a fade.", C: "Decorative is unrelated.", D: "They plan around a real fade." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "The city ______ the contractor after the third missed inspection, citing the clause on safety delays." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "dismissed", B: "rewarded", C: "sang to", D: "ignored" }, answer: "A", explain: { correct: "Dismissed means fired; missed inspections plus a safety clause fit termination.", wrong: { B: "Rewarded would not follow missed inspections.", C: "Sang is unrelated.", D: "Citing a clause is not ignoring." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The novel’s humor is ______, a dry remark every few pages rather than a comic set piece." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "intermittent", B: "nonstop", C: "absent", D: "illegal" }, answer: "A", explain: { correct: "Intermittent means occurring at intervals; a dry remark every few pages fits.", wrong: { B: "Nonstop would be set-piece density.", C: "Remarks exist, so not absent.", D: "Humor is not a legal issue here." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Coral ______ after the water stayed too warm for weeks, leaving white skeletons where color had been." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "bleached", B: "flourished", C: "migrated inland", D: "was painted" }, answer: "A", explain: { correct: "Bleached means lost color from stress; white skeletons after heat fit.", wrong: { B: "Flourished would keep color.", C: "Coral does not move inland as a reef.", D: "Painted is not the biological process." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The headline ______ causality, implying the vaccine caused the symptom that the study had only found alongside it." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "implied", B: "denied all", C: "rhymed", D: "omitted by not running" }, answer: "A", explain: { correct: "Implied causality means it suggested cause without the study proving it; “alongside” versus “caused” is the error. Wait, the blank is \"The headline ______ causality\" so implied works.", wrong: { B: "Denied all causality would be the opposite error.", C: "Rhymed is poetic.", D: "The headline ran." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Statisticians ______ the analysis after finding that a coding error had reversed two columns." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "reran", B: "published unchanged", C: "sang", D: "sold" }, answer: "A", explain: { correct: "Reran means ran again; reversed columns require a new analysis.", wrong: { B: "Unchanged publication would keep the error.", C: "Sang is unrelated.", D: "Sold is commercial." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A “climate-ready” waterfront park that has no escape route at high tide is a postcard. Readiness is a path that still exists when the path you took in is underwater." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To define climate readiness as remaining access, not as a pretty park label", B: "To sell postcards", C: "To deny that tides exist", D: "To teach landscape painting" }, answer: "A", explain: { correct: "No escape at high tide, postcard, path that exists when the entry is underwater.", wrong: { B: "Postcard is a metaphor.", C: "Tides are the test.", D: "Not painting." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "A citation to “ibid.” that points to the wrong page is a small crack. Small cracks are how readers lose a chain of evidence." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It explains why the small error matters", B: "It defines ibid. as a person", C: "It lists pages", D: "It praises all cracks in masonry" }, answer: "A", explain: { correct: "Losing a chain of evidence is why a wrong ibid. page is not trivial.", wrong: { B: "Ibid. is a citation term.", C: "No list appears.", D: "Crack is metaphorical." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Ask for the model. Ask for the training data. Ask who was harmed by its mistakes. A tool without those answers is a vendor slide." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "Three requests that distinguish a real tool from marketing", B: "A vendor as a street seller only", C: "A training as a gym plan", D: "A slide as playground equipment" }, answer: "A", explain: { correct: "Model, data, harm, then vendor slide if unanswered.", wrong: { B: "Vendor slide means sales deck.", C: "Training data is ML data.", D: "Slide means presentation." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Congestion fees should be spent inside the zone that pays them, or the political coalition collapses." }, { label: "Text 2", body: "Spending only inside the zone can starve the bus routes that feed the zone from poorer suburbs. A split—half in-zone, half on feeder routes—keeps both the coalition and the people who arrive by bus." }], prompt: "Which choice best describes the relationship between the texts?", choices: { A: "Text 2 accepts coalition politics but widens who should receive the funds", B: "Text 2 rejects all congestion fees", C: "Text 1 discusses only rural farms", D: "Both ignore buses" }, answer: "A", explain: { correct: "Text 2 still cares about the coalition, then adds feeder-route spending for suburban bus riders.", wrong: { B: "A split still uses the fees.", C: "Text 1 is about the paying zone, typically urban.", D: "Text 2 centers buses." } } }
  ]
},
{
  day: 45, date: "2026-11-02",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The snowpack was ______ for May, and reservoir managers cut allocations a month earlier than usual." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "meager", B: "record-breaking in depth", C: "theoretical", D: "decorative" }, answer: "A", explain: { correct: "Meager means scant; early cuts in allocations fit a thin May snowpack.", wrong: { B: "Record depth would not force early cuts.", C: "Managers are responding to real snow.", D: "Decorative is unrelated." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Investigators ______ the emails in date order, which made the shifting story visible." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "arranged", B: "shredded", C: "sang", D: "sold" }, answer: "A", explain: { correct: "Arranged in date order is sorting; a shifting story becoming visible fits.", wrong: { B: "Shredded emails would hide the story.", C: "Sang is unrelated.", D: "Sold is commercial." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The critic was ______ of masterpiece talk, preferring to say what a work did on Tuesday night in a specific room." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "wary", B: "fond", C: "unaware", D: "silent" }, answer: "A", explain: { correct: "Wary means cautious; preferring Tuesday-night specifics over masterpiece talk fits distrust of the big word.", wrong: { B: "Fond of masterpiece talk would use it.", C: "The critic knows the talk and avoids it.", D: "Preferring to say something is not silence." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Mussels ______ the pilings, a living crust that engineers had to scrape before they could inspect the steel." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "encrusted", B: "avoided", C: "translated", D: "ignored" }, answer: "A", explain: { correct: "Encrusted means covered with a crust; a living crust needing scraping fits.", wrong: { B: "Avoided pilings would not create a crust on them.", C: "Translate is language.", D: "Engineers must deal with the mussels, so they are present." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The author’s ______—“we” for a study of twelve people—irritated readers who were not in the lab." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "pronoun", B: "equation", C: "silence", D: "rhyme" }, answer: "A", explain: { correct: "Pronoun “we” overreaching from twelve people is the irritation.", wrong: { B: "Equation is not “we.”", C: "Using “we” is not silence.", D: "Rhyme is verse." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "The two thermometers ______ by two degrees, so the team reported both readings." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "differed", B: "matched exactly", C: "melted", D: "sang" }, answer: "A", explain: { correct: "Differed by two degrees explains reporting both.", wrong: { B: "Exact matching would allow one number.", C: "Melted is not indicated.", D: "Sang is unrelated." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A “smart city” pitch that never mentions maintenance crews is a demo. Sensors without people who replace them are a future that rusts." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To insist that smart-city claims include the labor of upkeep", B: "To sell sensors", C: "To deny that cities rust", D: "To teach demos as theater only without critique" }, answer: "A", explain: { correct: "Pitch without crews, demo, sensors without replacers rust.", wrong: { B: "Sensors without people are the problem.", C: "Rust is the warning.", D: "Demo is criticized, not taught as sufficient." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "“Full disclosure” that arrives after the vote is not disclosure. It is a press release with a conscience costume." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It recasts late disclosure as public relations rather than information", B: "It defines costumes in theater class", C: "It lists votes", D: "It praises all press releases" }, answer: "A", explain: { correct: "Press release with a conscience costume means PR, not real disclosure.", wrong: { B: "Costume is metaphorical.", C: "No list appears.", D: "Press release is the insult." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Write the rule. Write the exception. Write who knows the exception. Unequal knowledge of loopholes is a second law." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "Three writings that reveal a hidden inequality in how rules work", B: "A loophole as a sewing guide", C: "A law as a courtroom drama", D: "An exception as a grammar worksheet" }, answer: "A", explain: { correct: "Rule, exception, who knows it, then unequal knowledge as a second law.", wrong: { B: "Loophole is legal/policy.", C: "Not a drama.", D: "Not grammar." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "National service should include climate work—restoring wetlands, not only folding flags." }, { label: "Text 2", body: "Wetland restoration is skilled labor. A one-year corps that plants the wrong species can do harm. If climate work is included, it needs botanists on staff, not only a patriotic caption." }], prompt: "Text 2 would most likely", choices: { A: "allow climate tasks in service only if expertise prevents ecological harm", B: "ban all wetland work forever", C: "claim flags are wetlands", D: "deny that species matter" }, answer: "A", explain: { correct: "Text 2 warns about wrong species and requires botanists if climate work is included.", wrong: { B: "Inclusion is conditional, not a total ban.", C: "Flags are Text 1’s contrast, not Text 2’s claim.", D: "Wrong species is the harm." } } }
  ]
},
{
  day: 46, date: "2026-11-03",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The tide was ______ than the chart, pushed by a wind that had not been in the forecast." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "higher", B: "identical to", C: "theoretical", D: "decorative" }, answer: "A", explain: { correct: "Higher than the chart because of unforecast wind fits a setup above prediction.", wrong: { B: "Identical would match the chart.", C: "Wind and tide are treated as real.", D: "Decorative is unrelated." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "The museum ______ the label after descendants objected to the word “discovered.”" }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "rewrote", B: "enlarged the same wording", C: "sang", D: "sold" }, answer: "A", explain: { correct: "Rewrote the label in response to an objection about “discovered.”", wrong: { B: "Enlarging the same wording would not address the objection.", C: "Sang is unrelated.", D: "Sold is commercial." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The memoir’s ______ of receipts—rent, bus, clinic—does more to explain the year than any single dramatic scene." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "inventory", B: "erasure", C: "melody", D: "silence" }, answer: "A", explain: { correct: "Inventory means a listing; rent, bus, clinic receipts as explanation fit.", wrong: { B: "Erasure would remove receipts.", C: "Melody is music.", D: "Listing receipts is not silence." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Otters ______ urchin density, which allowed kelp to return in surveys five years later." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "reduced", B: "maximized", C: "ignored", D: "translated" }, answer: "A", explain: { correct: "Reduced urchin density lets kelp return.", wrong: { B: "Maximized urchins would mow kelp.", C: "The causal chain is not ignoring.", D: "Translate is language." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The metaphor ______ when it called data “the new oil,” because spilled oil and leaked records harm different bodies." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "faltered", B: "became exact", C: "went unspoken", D: "rhymed perfectly" }, answer: "A", explain: { correct: "Faltered means lost strength; different harms show the metaphor failing.", wrong: { B: "Exact would mean the likeness held throughout.", C: "The metaphor was used.", D: "Rhyme is not the issue." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Labs ______ samples on dry ice across three time zones so that the assay still saw intact proteins." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "transported", B: "discarded", C: "exhibited as sculpture", D: "ignored" }, answer: "A", explain: { correct: "Transported on dry ice to keep proteins intact is shipping with cold chain.", wrong: { B: "Discarded samples would not be assayed.", C: "Sculpture is not the assay goal.", D: "They are preserving samples for use." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A “neutral” algorithm trained on past arrests will replay past policing. Neutrality that copies a biased archive is not neutrality. It is a loop with better branding." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To argue that training on biased records undermines claims of algorithmic neutrality", B: "To sell branding", C: "To deny that arrests are recorded", D: "To teach loops in programming only as syntax" }, answer: "A", explain: { correct: "Past arrests, copy of biased archive, loop with branding.", wrong: { B: "Branding is the insult.", C: "Records are the training source.", D: "Loop is a social replay, not a syntax lesson." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "A dedication that names a funder in the same breath as a child can be honest. It can also be how money buys a family tone. Read the grant number." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It tells readers how to check the money behind the tone", B: "It lists children", C: "It bans dedications", D: "It defines breath in physiology" }, answer: "A", explain: { correct: "Read the grant number is the check on whether money bought the family tone.", wrong: { B: "No list appears.", C: "Honest dedications are allowed.", D: "Breath is idiomatic." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "State the rumor’s first date. State the correction’s first date. State the gap. Speed is the ethics." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "Two dates and a gap that redefine ethics as timing", B: "A calendar as a gift shop item", C: "A rumor as a folklore course", D: "A gap as a dentistry ad" }, answer: "A", explain: { correct: "Rumor date, correction date, gap, then speed as ethics.", wrong: { B: "Dates are evidence, not merchandise.", C: "Not a folklore syllabus.", D: "Gap means time between stories." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Urban tree giveaways should prioritize the hottest census blocks, even if those households have less yard space." }, { label: "Text 2", body: "A seedling in a baking yard without water rights is a future stump. Pair the hottest-block rule with soil, hose access, and a three-year watering crew, or the giveaway is a photo." }], prompt: "Text 2 would most likely modify Text 1 by", choices: { A: "keeping the heat-priority but adding what a tree needs to live there", B: "planting only in already-cool yards", C: "banning all giveaways", D: "ignoring water" }, answer: "A", explain: { correct: "Hottest-block rule plus soil, hose, watering crew—heat stays, survival is added.", wrong: { B: "Hottest blocks remain the target.", C: "Giveaway continues with support.", D: "Hose and watering are required." } } }
  ]
},
{
  day: 47, date: "2026-11-04",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The ice road was ______ by noon, and trucks had to finish crossings at dawn." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "softening", B: "thickening", C: "theoretical", D: "decorative" }, answer: "A", explain: { correct: "Softening by noon explains dawn-only crossings.", wrong: { B: "Thickening would allow later crossings.", C: "Trucks are on a real road.", D: "Decorative is unrelated." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "The paper ______ a limitation in sentence form, which was easy to skip, instead of in a labeled box." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "buried", B: "highlighted", C: "sang", D: "sold" }, answer: "A", explain: { correct: "Buried in a skippable sentence versus a labeled box is hiding in plain sight.", wrong: { B: "Highlighted would use the box.", C: "Sang is unrelated.", D: "Sold is commercial." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The play’s politics are ______, arriving through who gets the last word rather than through a speech about justice." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "implicit", B: "sermonizing", C: "absent", D: "rhymed only" }, answer: "A", explain: { correct: "Implicit means not stated directly; last-word structure versus a justice speech fits.", wrong: { B: "Sermonizing would be the justice speech.", C: "Politics arriving somehow are not absent.", D: "Rhyme is not the vehicle named." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Dunes ______ the inland lots until fences failed, then sand arrived in living rooms." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "threatened", B: "protected forever", C: "ignored", D: "translated" }, answer: "A", explain: { correct: "Threatened until fences failed, then sand in rooms, is a real risk realized.", wrong: { B: "Forever protection contradicts living-room sand.", C: "The dunes are acting on lots.", D: "Translate is language." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The author’s ______ of “simply”—as in “simply implement”—hid the years of staffing the plan would take." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "use", B: "avoidance", C: "translation into Latin", D: "silence" }, answer: "A", explain: { correct: "Use of “simply” is what hid staffing years.", wrong: { B: "Avoidance of the word would not hide the years that way.", C: "Latin is unrelated.", D: "Using the word is not silence." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Reviewers ______ raw images after a figure looked too clean to be a single exposure." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "requested", B: "forbade seeing", C: "composed as music", D: "photographed themselves instead" }, answer: "A", explain: { correct: "Requested raw images to check a too-clean figure is standard scrutiny.", wrong: { B: "They want to see more, not forbid seeing.", C: "Music is unrelated.", D: "The issue is the paper’s figure." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A “complete streets” ribbon-cutting that leaves a highway on-ramp unmarked for people on foot is a photo. Completeness is the last hundred feet." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To locate real completeness in leftover dangerous segments, not in ceremonies", B: "To sell ribbons", C: "To deny that streets can be walked", D: "To teach photography" }, answer: "A", explain: { correct: "Ribbon-cutting versus unmarked on-ramp, last hundred feet.", wrong: { B: "Ribbon is the ceremony.", C: "Walking is the missing design.", D: "Photo is a metaphor for empty optics." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "“As I have shown” in paragraph two is a hope. Showing is what the rest of the paper is for." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It postpones proof until the paper actually argues", B: "It lists paragraphs", C: "It praises all early boasts", D: "It defines hope in psychology only" }, answer: "A", explain: { correct: "The rest of the paper is for showing, so paragraph two has not yet shown.", wrong: { B: "No list appears.", C: "Early “as I have shown” is treated as premature.", D: "Hope is rhetorical." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Name the leak. Name the tank. Name the creek. A spill with no names is a weather event, and it is not." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "Three namings that refuse to treat a spill as uncaused weather", B: "A weather forecast", C: "A tank as a military history", D: "A creek as a hiking ad" }, answer: "A", explain: { correct: "Leak, tank, creek, then not weather.", wrong: { B: "Weather is the false frame.", C: "Tank means storage.", D: "Creek is the receiving water." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Open-office plans should be abandoned. Measured focus hours collapse, and the promised collisions are mostly interruptions." }, { label: "Text 2", body: "Abandoning open rooms without building quiet rooms just recreates the cave. A floor can be mixed: focus rooms by default, a small collision zone that is optional. The error was making interruption the architecture." }], prompt: "The author of Text 2 would most likely", choices: { A: "reject interruption-as-default but keep some optional shared space", B: "defend interruption as the goal of all floors", C: "claim focus hours do not matter", D: "deny that rooms can be built" }, answer: "A", explain: { correct: "Text 2 wants focus rooms by default and optional collision zones; interruption should not be the architecture.", wrong: { B: "That is the error Text 2 names.", C: "Focus rooms are the default, so focus matters.", D: "Building quiet rooms is the alternative to mere abandonment." } } }
  ]
},
{
  day: 48, date: "2026-11-05",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The harbor’s channel markers were ______ in the fog, and captains slowed to a crawl." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "invisible", B: "brighter than usual", C: "theoretical", D: "decorative only in sunlight" }, answer: "A", explain: { correct: "Invisible in fog explains slowing to a crawl.", wrong: { B: "Brighter would not force a crawl.", C: "Captains respond to real fog.", D: "The issue is fog, not a sunlight-only decoration theory." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "The board ______ public comment into a written portal, which excluded people without reliable internet." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "moved", B: "expanded to every street corner", C: "sang", D: "ignored by canceling the issue" }, answer: "A", explain: { correct: "Moved comment into a portal is a change of venue that can exclude.", wrong: { B: "Street corners would be more accessible, not less.", C: "Sang is unrelated.", D: "The issue still exists; the venue changed." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The biography ______ gossip, requiring a second source before a party story enters the chapter." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "distrusts", B: "relishes unchecked", C: "sets to music", D: "omits all social life from" }, answer: "A", explain: { correct: "Distrusts gossip by requiring a second source.", wrong: { B: "Relishing unchecked gossip would skip the second source.", C: "Music is unrelated.", D: "Party stories can enter with backing; social life is not fully omitted." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Seagrass ______ wave energy on the inner reef, a service storms made newly obvious." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "absorbs", B: "increases", C: "ignores", D: "patents" }, answer: "A", explain: { correct: "Absorbs wave energy is a coastal protection service.", wrong: { B: "Increases would worsen storms’ punch.", C: "The service is physical work.", D: "Patents are legal." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The analogy ______ a pandemic as a war, which licensed emergency powers and also licensed forgetting the dead’s names." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "framed", B: "refused", C: "rhymed", D: "unspoke" }, answer: "A", explain: { correct: "Framed as means presented as; war-frame licensing powers and forgetting names fits.", wrong: { B: "The analogy did present it as war.", C: "Rhymed is verse.", D: "Unspoke is not the verb; the frame was used." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Two satellites ______ the same methane plume, which made a ground-sensor error less plausible." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "detected", B: "invented", C: "sang", D: "sold" }, answer: "A", explain: { correct: "Detected independently by two satellites weakens a single-sensor error story.", wrong: { B: "Invented would not be two instruments agreeing.", C: "Sang is unrelated.", D: "Sold is commercial." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A “resilient” grid that has no spare transformers is a press release. Resilience is a warehouse and a crew that can drive at 2 a.m." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To define grid resilience as parts and labor, not as a label", B: "To sell press releases", C: "To deny that grids fail", D: "To teach driving" }, answer: "A", explain: { correct: "No spare transformers, press release, warehouse and 2 a.m. crew.", wrong: { B: "Press release is the empty version.", C: "Failure is why spares matter.", D: "Driving is the crew’s job, not a lesson." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "“It is obvious that” is a closed fist. Open it by asking for the measurement that made it obvious." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It gives a method for forcing evidence out of a bluff", B: "It defines fists in anatomy", C: "It lists measurements", D: "It agrees that nothing need be measured" }, answer: "A", explain: { correct: "Ask for the measurement is how to open the closed fist of “obvious.”", wrong: { B: "Fist is metaphorical.", C: "No list appears.", D: "The method demands a measurement." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Copy the abstract. Cover the result. Guess the result from the method alone. If you cannot, the method was not a method." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "A blinding test that judges whether methods actually determine results", B: "An abstract as modern art", C: "A guess as a carnival game", D: "A cover as a bedspread ad" }, answer: "A", explain: { correct: "Copy, cover result, guess from method; failure means no real method.", wrong: { B: "Abstract means paper summary.", C: "Guess is diagnostic.", D: "Cover means hide." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Congestion pricing should exempt small businesses’ delivery vans, or main streets will lose their shops." }, { label: "Text 2", body: "A van exemption that is not time-windowed becomes a permanent double-park. Exempt off-hour deliveries, not the vehicle type. Shops need goods; they also need a curb that is not a loading dock all afternoon." }], prompt: "Text 2 would most likely", choices: { A: "protect shop deliveries by time of day rather than by a blanket van exemption", B: "ban all shop deliveries", C: "deny that main streets have shops", D: "claim curbs cannot be used" }, answer: "A", explain: { correct: "Exempt off-hour deliveries, not vehicle type; curb still needs to function.", wrong: { B: "Goods still need to arrive.", C: "Shops are why both authors care.", D: "Curb use is the design problem." } } }
  ]
},
{
  day: 49, date: "2026-11-06",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The trail was ______ with downed limbs after the ice storm, and the first mile took twice the usual time." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "obstructed", B: "cleared already", C: "theoretical", D: "paved" }, answer: "A", explain: { correct: "Obstructed with limbs explains a slower first mile.", wrong: { B: "Already cleared would not slow hikers.", C: "An ice storm’s limbs are real.", D: "Paved is not about limbs." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "The agency ______ its earlier map after new lidar showed the floodplain was wider than the 1980s drawing." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "updated", B: "framed as art only", C: "sang", D: "ignored" }, answer: "A", explain: { correct: "Updated the map when lidar showed a wider floodplain.", wrong: { B: "Art framing is not a floodplain revision.", C: "Sang is unrelated.", D: "They changed the map, so they did not ignore lidar." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The novel is ______ about money, tracking debts the way other books track kisses." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "serious", B: "evasive", C: "silent", D: "rhymed" }, answer: "A", explain: { correct: "Serious about money means it treats debts as central, like kisses in other books.", wrong: { B: "Evasive would avoid debts.", C: "Tracking debts is not silence.", D: "Rhymed is form." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Invasive carp ______ native fish by stripping plankton that the natives needed as fry." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "outcompeted", B: "protected", C: "catalogued as pets", D: "ignored" }, answer: "A", explain: { correct: "Outcompeted means won the resource contest; stripping plankton from fry fits.", wrong: { B: "Protected natives would not strip their food.", C: "Pets are not the ecological claim.", D: "The carp are having an effect." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The author’s ______—“obviously” attached to a contested claim—did the opposite of making it obvious." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "adverb", B: "footnote", C: "silence", D: "table" }, answer: "A", explain: { correct: "Adverb “obviously” on a contested claim undercuts itself.", wrong: { B: "The quoted word is an adverb, not a footnote.", C: "Saying “obviously” is not silence.", D: "Table is not “obviously.”" } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Clinicians ______ enrollment when they saw that one clinic’s patients were dominating the sample." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "paused", B: "doubled at that clinic only", C: "sang", D: "sold" }, answer: "A", explain: { correct: "Paused enrollment to fix domination by one clinic is a sampling correction.", wrong: { B: "Doubling that clinic would worsen domination.", C: "Sang is unrelated.", D: "Sold is commercial." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A “historic” tax credit that renovates facades and raises rents is a transfer. History, in that case, is a luxury good with old brick." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To recast some preservation subsidies as transfers that price people out", B: "To sell brick", C: "To deny that facades can be renovated", D: "To teach tax accounting in full" }, answer: "A", explain: { correct: "Credit, raised rents, transfer, history as luxury brick.", wrong: { B: "Brick is the surface of the luxury good.", C: "Renovation happens; the issue is rents.", D: "Not a full accounting course." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "A methods paragraph that says “standard procedures were followed” without naming them is a locked cabinet. Name the procedure or admit you are asking for trust." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It forces a choice between specificity and an honest request for trust", B: "It lists procedures", C: "It praises all cabinets", D: "It defines trust in psychology only" }, answer: "A", explain: { correct: "Name it or admit you want trust is the choice after the locked cabinet image.", wrong: { B: "No list appears.", C: "Cabinet is the problem.", D: "Trust is methodological." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Plot the fine. Plot who paid it. Plot who did not get fined for the same act. Enforcement is a map of power." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "Three plots that define enforcement as unequal power", B: "A fine as an art show", C: "A map as a gas-station giveaway", D: "An act as a play script" }, answer: "A", explain: { correct: "Fine, who paid, who did not, then power map.", wrong: { B: "Fine means penalty.", C: "Map is analytical.", D: "Act means the behavior fined." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Public comments should be capped at two minutes so that more people can speak." }, { label: "Text 2", body: "Two minutes flattens anyone whose point needs a story. A lottery for ten three-minute slots, plus a written record that is actually read, beats a long line of slogans. Quantity of speakers is not the same as quality of hearing." }], prompt: "Which choice best describes the difference in what “more voice” means?", choices: { A: "Text 1 counts more speakers; Text 2 cares whether complex points can be heard", B: "Text 2 wants no one to speak", C: "Text 1 bans written records", D: "Both ignore time" }, answer: "A", explain: { correct: "Text 1 uses a cap to increase headcount; Text 2 says slogans are not hearing.", wrong: { B: "Text 2 still wants slots.", C: "Text 1 does not ban writing; Text 2 wants writing read.", D: "Both are about time limits." } } }
  ]
},
{
  day: 50, date: "2026-11-07",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The clinic’s backup power was ______ for lights but not for the vaccine fridge, a gap the outage made obvious." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "adequate", B: "sufficient for every device", C: "theoretical", D: "decorative" }, answer: "A", explain: { correct: "Adequate for lights but not the fridge is partial sufficiency.", wrong: { B: "Every device would include the fridge.", C: "The outage was real.", D: "Decorative is unrelated." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Editors ______ the correction on the same page as the original error, a rare courtesy." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "placed", B: "hid in a later issue only", C: "sang", D: "sold" }, answer: "A", explain: { correct: "Placed on the same page as the error is the courtesy named.", wrong: { B: "A later issue only would not be same-page.", C: "Sang is unrelated.", D: "Sold is commercial." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The narrator is ______ of her charm, which is why the charm curdles: she keeps pointing at it." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "too aware", B: "unconscious", C: "silent", D: "illiterate" }, answer: "A", explain: { correct: "Too aware, pointing at charm, makes it curdle.", wrong: { B: "Unconscious charm would not be pointed at.", C: "Pointing is not silence.", D: "Illiterate is unrelated." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Reefs ______ before seawalls fail, which is why some towns restore coral as infrastructure, not only as scenery." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "break waves", B: "amplify storms", C: "ignore coasts", D: "translate law" }, answer: "A", explain: { correct: "Break waves means reduce their force; treating coral as infrastructure fits.", wrong: { B: "Amplify would not justify restoration as infrastructure.", C: "They protect coasts.", D: "Law is unrelated." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The comparison was ______: it treated a household budget as a model for a currency-issuing state." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "inapposite", B: "exact", C: "unspoken", D: "musical" }, answer: "A", explain: { correct: "Inapposite means not appropriate; household versus currency-issuing state is a mismatch.", wrong: { B: "Exact would mean the model fit.", C: "The comparison was made.", D: "Musical is unrelated." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Researchers ______ a preregistration after realizing their flexible analysis paths could look like fishing." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "posted", B: "destroyed", C: "sang", D: "hid" }, answer: "A", explain: { correct: "Posted a preregistration to constrain fishing is the integrity move.", wrong: { B: "Destroyed would not constrain paths.", C: "Sang is unrelated.", D: "Hiding would worsen the fishing look." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A “walkable” score that ignores night lighting will praise a street you cannot see. Walkability is a Tuesday at 9 p.m., not a noon audit." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To argue that walkability must include after-dark conditions, not only daytime checklists", B: "To sell lights", C: "To deny that people walk", D: "To teach scoring as sports only" }, answer: "A", explain: { correct: "Night lighting, street you cannot see, Tuesday 9 p.m. versus noon audit.", wrong: { B: "Lighting is a condition, not a product pitch.", C: "Walking is assumed.", D: "Score means an index, not a game." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "“Beyond the scope of this paper” can be honest. It can also be how a hole is named so that no one asks you to fill it. Scope is a tool and a shield." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It names the double use of “scope” after giving both a defense and a suspicion", B: "It lists papers", C: "It praises all holes", D: "It defines shields in metallurgy" }, answer: "A", explain: { correct: "Tool and shield compress honest limit versus named hole.", wrong: { B: "No list appears.", C: "Holes can be evasions.", D: "Shield is metaphorical." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Take the official total. Subtract the double-counted. Add the never-visited. A census is an argument about those three numbers." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "An arithmetic of correction that ends by defining a census as an argument", B: "A census as a Roman history", C: "A visit as a social call only", D: "A total as a sports scoreboard" }, answer: "A", explain: { correct: "Total, subtract doubles, add missed, then census as argument.", wrong: { B: "Not Roman history.", C: "Never-visited means uncounted people.", D: "Not sports." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Standardized tests should stay in admissions because teacher grades inflate at different rates by school." }, { label: "Text 2", body: "Inflation is real, and a test that tracks zip code as tightly as algebra is not a clean substitute. Keep a test and contextualize it, or drop it and audit transcripts harder. The error is calling either number a pure skill thermometer." }], prompt: "The author of Text 2 would most likely", choices: { A: "grant grade inflation but reject treating the test as a neutral skill measure", B: "claim grades never inflate", C: "argue that zip codes are algebra", D: "insist only one number can ever be used" }, answer: "A", explain: { correct: "Text 2 says inflation is real (granting Text 1) then says the test tracks zip code, so neither number is a pure thermometer.", wrong: { B: "Inflation is granted.", C: "Zip code versus algebra is the tracking problem, not an identity.", D: "Keep-and-contextualize or drop-and-audit are two paths." } } }
  ]
}
);
