window.SAT_DAYS = window.SAT_DAYS || [];
window.SAT_DAYS.push(
{
  day: 31, date: "2026-10-19",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The mayor’s promise was ______ until a dollar amount appeared in the budget, not just in a speech." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "aspirational", B: "already spent", C: "illegal on its face", D: "rhymed" }, answer: "A", explain: { correct: "Aspirational means hoped-for rather than secured; a speech without a budget line fits.", wrong: { B: "Already spent would mean money moved, unlike a mere speech.", C: "A speech promise is not automatically illegal.", D: "Rhymed is poetic." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Researchers ______ pollen from lake mud to reconstruct which trees had stood on the shore a thousand years ago." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "extracted", B: "ignored", C: "composed as music", D: "sold as perfume only" }, answer: "A", explain: { correct: "Extracted means taken out; pulling pollen from mud for reconstruction fits.", wrong: { B: "Ignoring pollen would not reconstruct trees.", C: "Music is unrelated.", D: "Perfume is not the scientific aim." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The novel’s narrator is ______ of her own charm, which makes the charm more irritating, not less." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "conscious", B: "unaware", C: "silent", D: "illiterate" }, answer: "A", explain: { correct: "Conscious of her own charm means she knows it; knowing and still deploying it can irritate.", wrong: { B: "Unaware charm would not be self-aware in the way the sentence describes.", C: "A narrator speaking is not silent.", D: "Illiterate is unrelated." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "New bike lanes ______ car travel time by under a minute in the study, while injuries at those corners fell sharply." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "increased", B: "erased all", C: "set to music", D: "translated" }, answer: "A", explain: { correct: "Increased by under a minute is a small rise in car time beside a sharp injury drop.", wrong: { B: "Under a minute is not erasing all travel time.", C: "Music is unrelated.", D: "Translated is language." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "His summary ______ a key caveat, so readers thought the drug worked in all ages when it had been tested only in adults." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "omitted", B: "emphasized", C: "rhymed", D: "photographed" }, answer: "A", explain: { correct: "Omitted means left out; missing the age caveat caused the overgeneralization.", wrong: { B: "Emphasized would highlight the caveat.", C: "Rhymed is poetic.", D: "Photographed is irrelevant." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "The two accounts were ______ on the sequence of shots, which allowed investigators to build a single timeline." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "aligned", B: "irreconcilable", C: "silent", D: "fictional by agreement" }, answer: "A", explain: { correct: "Aligned means in agreement; matching sequences enabling one timeline fits.", wrong: { B: "Irreconcilable accounts would block a single timeline.", C: "Accounts that give sequences are not silent.", D: "Investigators treat them as usable, not as agreed fiction." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A “food desert” map that counts stores but not bus lines will misread a neighborhood. Access is a route, not a dot. Put the map on a schedule, or you have drawn shelves without doors." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To argue that access maps must include how people actually travel", B: "To sell groceries", C: "To deny that stores exist", D: "To teach desert ecology" }, answer: "A", explain: { correct: "Stores versus bus lines, route not dot, shelves without doors.", wrong: { B: "No grocery ad appears.", C: "Stores are counted as real.", D: "Desert is a metaphor." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "An epilogue that ties every thread can be a gift. It can also be a refusal to let the reader do any remaining work. Closure is a service and a control." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It names the double nature of narrative closure", B: "It lists threads", C: "It bans epilogues", D: "It defines work as employment only" }, answer: "A", explain: { correct: "Service and control compress gift versus refusal to let the reader work.", wrong: { B: "No list appears.", C: "Epilogues can still be gifts.", D: "Work means interpretive labor." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Write the methods so a rival could copy them. If a rival cannot copy them, you have written a vibe, not a protocol." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "A standard for methods, then a diagnosis of writing that fails it", B: "A rivalry as a sports recap", C: "A protocol as a diplomatic treaty only", D: "A recipe for vibes as a product" }, answer: "A", explain: { correct: "Copyable methods versus vibe if they cannot be copied.", wrong: { B: "Rival is scientific, not a game recap.", C: "Protocol means procedure.", D: "Vibe is the failure mode." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Urban highways that sliced neighborhoods should be removed and replaced with streets. The original cuts were political, and undoing them is repair." }, { label: "Text 2", body: "Removal without transit capacity can recreate the jam on surface streets that the highway once hid. Repair is not only demolition. It is a network that still moves people who did not choose the original cut." }], prompt: "Text 2 would most likely", choices: { A: "support repair as a goal but insist it include how people still need to move", B: "claim neighborhoods were never sliced", C: "argue that all highways must stay forever unchanged", D: "deny that people travel" }, answer: "A", explain: { correct: "Text 2 says repair is not only demolition and must still move people.", wrong: { B: "Text 2 does not deny the cuts.", C: "Text 2 allows removal if capacity is addressed.", D: "Moving people is Text 2’s concern." } } }
  ]
},
{
  day: 32, date: "2026-10-20",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The island’s radio link was ______ during storms, so the clinic kept a paper backup for prescriptions." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "intermittent", B: "perfect", C: "decorative", D: "theoretical" }, answer: "A", explain: { correct: "Intermittent means on and off; storms plus a paper backup fit an unreliable link.", wrong: { B: "Perfect links would not need paper backups for storms.", C: "Decorative is unrelated.", D: "The clinic’s backup treats the link as real but unreliable." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Curators ______ the attribution after a second signature appeared under infrared light." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "reconsidered", B: "ignored", C: "sang", D: "insured against seeing" }, answer: "A", explain: { correct: "Reconsidered means thought again; a newly visible signature forces a new look at who painted it.", wrong: { B: "They would not ignore a second signature.", C: "Sang is unrelated.", D: "They used infrared to see more, not to avoid seeing." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The essay’s tone is ______, almost bureaucratic, which makes its moral claims sting more than a sermon would." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "dry", B: "hysterical", C: "rhymed", D: "silent" }, answer: "A", explain: { correct: "Dry means unemotional in style; bureaucratic tone making morals sting fits.", wrong: { B: "Hysterical is the opposite of bureaucratic calm.", C: "Rhymed is form.", D: "An essay with claims is not silent." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Beavers ______ the stream into a chain of ponds, which then hosted amphibians the ranch had not seen in years." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "rewove", B: "drained completely", C: "paved", D: "translated" }, answer: "A", explain: { correct: "Rewove means reshaped into a new pattern; a chain of ponds from a stream fits.", wrong: { B: "Draining completely would not host amphibians in ponds.", C: "Paved is not what beavers do here.", D: "Translated is language." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "Opponents tried to ______ the bill as a tax on breathing, a slogan that skipped the actual fee schedule." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "caricature", B: "summarize faithfully", C: "fund", D: "notarize" }, answer: "A", explain: { correct: "Caricature means distort into an extreme cartoon; “tax on breathing” skipping the fee schedule fits.", wrong: { B: "Faithful summary would use the fee schedule.", C: "Fund is financial support, not labeling.", D: "Notarize is a stamp." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "The two labs ______ their protocols so that a failure in one could be checked as a true failure, not a difference in steps." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "harmonized", B: "secreted", C: "rhymed", D: "sold" }, answer: "A", explain: { correct: "Harmonized means made consistent; matching protocols so failures are comparable fits.", wrong: { B: "Secreted would hide protocols.", C: "Rhymed is poetic.", D: "Sold is commercial." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A “walkable” neighborhood on a brochure can still lack a sidewalk on the side where people actually wait for the bus. Walkability is not a font. It is a curb that exists on a Tuesday in the rain." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To contrast marketing language with the physical conditions of walking", B: "To sell fonts", C: "To deny that buses run", D: "To teach concrete chemistry" }, answer: "A", explain: { correct: "Brochure versus missing sidewalk, font versus Tuesday rain curb.", wrong: { B: "Font is a metaphor for empty styling.", C: "Bus waiting is assumed real.", D: "Curbs are named, not formulated." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "A preface that apologizes for the book’s existence is often a request for mercy. Sometimes it is also an accurate warning. Readers should decide which after chapter two, not after the apology." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It tells readers when to judge the apology’s honesty", B: "It bans prefaces", C: "It summarizes chapter two", D: "It defines mercy legally" }, answer: "A", explain: { correct: "Decide after chapter two, not after the apology, is timing for judgment.", wrong: { B: "Prefaces are to be tested, not banned.", C: "Chapter two is a checkpoint, not summarized.", D: "Mercy is not a legal term here." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Collect the rumor. Collect the correction. Collect the number of people who saw each. Distribution, not intention, is often the harm." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "Two collections plus a reach comparison, then a claim about where harm sits", B: "A rumor as a literary genre guide", C: "A math textbook chapter on intention", D: "A postal manual" }, answer: "A", explain: { correct: "Rumor, correction, counts of viewers, then distribution as harm.", wrong: { B: "Not a genre guide.", C: "Intention is downplayed, not taught as a course.", D: "Distribution is of attention, not mail." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "College athletes should be paid by schools. The current system extracts labor while calling it amateur character-building." }, { label: "Text 2", body: "Pay without a plan for Title IX, walk-ons, and non-revenue sports will recreate a booster market inside the athletic department. Compensation can be just; it still has to be designed, not merely announced as a moral slogan." }], prompt: "Which choice best describes the difference between the texts?", choices: { A: "Text 1 states a moral claim for pay; Text 2 focuses on design problems that follow if pay arrives", B: "Text 2 denies that athletes work", C: "Text 1 discusses only professors’ salaries", D: "Both reject any change to amateur rules" }, answer: "A", explain: { correct: "Text 1 is about extraction versus amateurism; Text 2 grants justice then flags Title IX and non-revenue design.", wrong: { B: "Text 2 treats compensation as potentially just.", C: "Text 1 is about athletes.", D: "Text 1 wants pay; Text 2 discusses how to design it." } } }
  ]
},
{
  day: 33, date: "2026-10-21",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The witness ______, then named the license plate, as if the pause had been a search through a mental file." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "hesitated", B: "sprinted", C: "sang", D: "left the country" }, answer: "A", explain: { correct: "Hesitated means paused; then naming the plate as if searching a file fits.", wrong: { B: "Sprinted is speed, not a pause.", C: "Sang is unrelated.", D: "Leaving the country is not in the sentence." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Conservationists ______ a corridor of private ranches so that pronghorn could still move south in winter." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "secured", B: "blocked with fencing only", C: "ignored", D: "translated" }, answer: "A", explain: { correct: "Secured means obtained or made safe; a corridor for winter movement fits.", wrong: { B: "Blocking with fencing would stop pronghorn.", C: "They arranged ranches, so they did not ignore the need.", D: "Translated is language." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The memoir’s ______ of the father’s voice—quoted at length, uncorrected—lets readers hear the cruelty without a narrator’s buffer." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "inclusion", B: "erasure", C: "translation into law", D: "musical setting" }, answer: "A", explain: { correct: "Inclusion of the voice quoted at length is what removes the buffer.", wrong: { B: "Erasure would not quote at length.", C: "Law is unrelated.", D: "Musical setting is not indicated." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "After the dam opened, sediment ______ downstream beaches that had been starving for sand." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "replenished", B: "erased from maps", C: "poisoned by definition", D: "ignored" }, answer: "A", explain: { correct: "Replenished means filled again; sand reaching starving beaches fits.", wrong: { B: "Beaches receiving sand are not erased.", C: "Sand supply is not defined as poison here.", D: "The sediment is doing work, not ignoring beaches." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The prosecutor’s analogy was ______: a household budget cannot print currency, and the city can." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "inapt", B: "perfect", C: "rhymed", D: "unspoken" }, answer: "A", explain: { correct: "Inapt means not suitable; a household-versus-city money difference makes the analogy a poor fit.", wrong: { B: "Perfect would require the comparison to hold.", C: "Rhymed is poetic.", D: "The analogy was offered, so not unspoken." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Peer reviewers ______ the authors to add a limitations paragraph after noticing the missing age group." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "urged", B: "forbade", C: "paid to delete", D: "sang to" }, answer: "A", explain: { correct: "Urged means strongly encouraged; asking for a limitations paragraph fits.", wrong: { B: "Forbade would block the paragraph.", C: "They want addition, not paid deletion.", D: "Sang is unrelated." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A historic-district rule that freezes facades but ignores rents will preserve walls for people who can no longer live behind them. Preservation without occupancy is a stage set." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To warn that saving appearances without addressing who can stay produces emptiness", B: "To teach facade painting", C: "To ban all historic rules", D: "To sell stage furniture" }, answer: "A", explain: { correct: "Facades versus rents, walls without residents, stage set.", wrong: { B: "No painting lesson appears.", C: "The target is incomplete preservation, not all rules.", D: "Stage set is a metaphor." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "“As everyone knows” is a closed door. It tries to make disagreement look like ignorance. Open the door by asking for the evidence everyone supposedly shares." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It offers a method for challenging the phrase analyzed above", B: "It lists everyone", C: "It defines doors in architecture", D: "It agrees that no evidence is needed" }, answer: "A", explain: { correct: "Ask for the shared evidence is the method to open the closed door of “as everyone knows.”", wrong: { B: "No roster appears.", C: "Door is metaphorical.", D: "The method asks for evidence." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Measure once with the cheap tool. Measure again with the expensive one only where the first tool screamed. Budgets are a research design." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "A two-stage measurement plan, then a claim that money shapes methods", B: "A tool catalog for hardware stores", C: "A scream as medical diagnosis", D: "A budget as a novel" }, answer: "A", explain: { correct: "Cheap then expensive where needed, then budgets as design.", wrong: { B: "Tools are a method, not a store list.", C: "Screamed is metaphorical for a strong signal.", D: "Not a novel." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Social media age limits should be hard bans under sixteen. Developing brains do not need a product designed to harvest attention." }, { label: "Text 2", body: "Hard bans push teenagers onto unmarked apps and shared logins. A delay on notifications, a default private account, and real enforcement against adult-to-minor contact change the product. Exile is not the only child-safety tool." }], prompt: "Text 2 would most likely characterize Text 1’s ban as", choices: { A: "well-intentioned but likely to drive use underground rather than redesign the product", B: "the only tool that works", C: "unrelated to attention", D: "a plan to harvest more attention" }, answer: "A", explain: { correct: "Text 2 says bans push teens to unmarked apps and prefers product changes plus enforcement.", wrong: { B: "Text 2 lists other tools.", C: "Both discuss youth and platforms.", D: "Text 1 opposes harvesting; Text 2 does not flip that into Text 1 harvesting." } } }
  ]
},
{
  day: 34, date: "2026-10-22",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The shoreline was ______ with wrack after the storm, a line of seagrass and bottles that marked the surge." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "littered", B: "empty of all objects", C: "paved", D: "theoretical" }, answer: "A", explain: { correct: "Littered with means covered with scattered matter; seagrass and bottles in a line fit.", wrong: { B: "Empty contradicts wrack.", C: "Paved is not a wrack line.", D: "The surge mark is treated as real." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Editors ______ the error in a correction box rather than pretending the first version had been perfect." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "acknowledged", B: "hid permanently", C: "set to music", D: "sold" }, answer: "A", explain: { correct: "Acknowledged means admitted; a correction box is an admission.", wrong: { B: "A public box is the opposite of hiding permanently.", C: "Music is unrelated.", D: "Sold is commercial." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The critic’s ______—she granted the film’s craft and still called the politics cowardly—felt more serious than a total pan." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "mixed verdict", B: "unconditional rave", C: "silence", D: "plot summary only" }, answer: "A", explain: { correct: "A mixed verdict grants some points and condemns others; craft plus cowardly politics fits.", wrong: { B: "A rave would not call the politics cowardly.", C: "She granted and called, so not silence.", D: "The sentence is evaluative, not mere plot." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Wolves ______ elk from the river bottoms, and the willows there began to return." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "displaced", B: "protected as pets", C: "named", D: "photographed harmlessly only" }, answer: "A", explain: { correct: "Displaced means pushed out; elk leaving bottoms so willows return is a classic trophic story.", wrong: { B: "Pets is not the ecological claim.", C: "Named would not move elk.", D: "Photos alone would not free the willows." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "His certainty was ______ by the third failed prediction, and the next paper was written in a humbler key." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "chastened", B: "inflated", C: "unrelated", D: "rhymed" }, answer: "A", explain: { correct: "Chastened means humbled; failed predictions then a humbler paper fit.", wrong: { B: "Inflated certainty would not yield a humbler key.", C: "The failures caused the change, so not unrelated.", D: "Rhymed is poetic." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "The samples were ______ in dry ice so that the proteins would not break down before the assay." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "shipped", B: "discarded", C: "displayed as art", D: "ignored" }, answer: "A", explain: { correct: "Shipped in dry ice to protect proteins is transport with preservation.", wrong: { B: "Discarded samples would not be assayed.", C: "Art display is not the assay goal.", D: "They are being preserved for use, not ignored." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A body camera is not a narrator. It is a lens with a height, a charge, and an off switch. Treat the footage as a document with limits, not as an all-seeing witness." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To limit what camera footage can prove by naming its physical and human constraints", B: "To sell cameras", C: "To deny that footage can ever be used", D: "To teach film editing as art only" }, answer: "A", explain: { correct: "Not a narrator; height, charge, off switch; document with limits.", wrong: { B: "No brand is sold.", C: "It is still a document, so usable with limits.", D: "Editing as art is not the civic point." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "The dedication “to my students, who taught me” can be sincere. It can also be a way to borrow their labor as a halo. Gratitude is a genre with motives." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It generalizes that thanks can serve mixed purposes", B: "It lists students", C: "It bans dedications", D: "It defines halo in optics" }, answer: "A", explain: { correct: "Genre with motives covers sincere thanks and borrowed halo.", wrong: { B: "No roster appears.", C: "Sincere dedications are allowed.", D: "Halo is metaphorical." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Plot the complaint. Plot the official response. Plot the third thing that actually happened. Minutes are a genre of fiction when they skip the third plot." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "Three plots, then a claim about minutes that omit the last", B: "A movie review of a film titled Minutes", C: "A clock-repair guide", D: "A legal form for complaints only" }, answer: "A", explain: { correct: "Complaint, response, actual event, then minutes as fiction if they skip the third.", wrong: { B: "Fiction is a critique of minutes, not a film.", C: "Minutes means meeting records.", D: "Not only a complaint form." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Municipal broadband should be public, like water. Private ISPs have underinvested in poor blocks because those blocks do not pay enough per mile." }, { label: "Text 2", body: "Public fiber can reach those blocks and can also stall in procurement. A city that cannot maintain pumps may not maintain nodes. Ownership is not competence. Pair the public mandate with an operator that has a record of uptime." }], prompt: "Text 2 would most likely", choices: { A: "agree that underserved blocks need service but warn that public ownership still requires operational skill", B: "deny that poor blocks exist", C: "claim water should be privatized as the model", D: "argue that uptime does not matter" }, answer: "A", explain: { correct: "Text 2 says public fiber can reach those blocks (aligning with the need) then flags procurement and uptime.", wrong: { B: "Those blocks are the point of service.", C: "Water is Text 1’s analogy; Text 2 does not flip it into privatizing water.", D: "Uptime is Text 2’s requirement." } } }
  ]
},
{
  day: 35, date: "2026-10-23",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The path down the dune was ______, each step filling with sand so that hikers left no lasting trail." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "ephemeral", B: "paved", C: "permanent in concrete", D: "theoretical" }, answer: "A", explain: { correct: "Ephemeral means short-lived; steps filling with sand so no lasting trail fits.", wrong: { B: "Paved paths last.", C: "Concrete permanence contradicts filling sand.", D: "Hikers are on a real dune." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "The board ______ the CEO after the third missed safety audit, naming an interim from operations." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "replaced", B: "promoted for the audits", C: "ignored", D: "set to music" }, answer: "A", explain: { correct: "Replaced means put someone else in the role; an interim from operations fits.", wrong: { B: "Missed audits would not earn a promotion.", C: "Naming an interim is not ignoring.", D: "Music is unrelated." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The poem’s ______—almost no adjectives—makes each verb do more work than a decorated line would." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: " spareness", B: "ornateness", C: "illegibility", D: "length" }, answer: "A", explain: { correct: "Spareness means few extra words; almost no adjectives fits. (Leading space in choice A should be \"spareness\".)", wrong: { B: "Ornateness would add adjectives.", C: "Illegibility is about reading the letters.", D: "Length is not the adjective count." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Oysters ______ the creek by filtering algae, a service the county later tried to value in dollars." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "cleared", B: "polluted", C: "ignored", D: "translated" }, answer: "A", explain: { correct: "Cleared by filtering algae is a cleaning service.", wrong: { B: "Filtering algae is not polluting.", C: "They are performing a service, not ignoring the creek.", D: "Translated is language." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The analogy ______ when it treated a pandemic as a war, because viruses do not sign treaties." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "broke down", B: "became perfect", C: "rhymed", D: "went unspoken" }, answer: "A", explain: { correct: "Broke down means failed; viruses not signing treaties is where the war analogy fails.", wrong: { B: "Perfect would mean the analogy held.", C: "Rhymed is poetic.", D: "The analogy was used, so not unspoken." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Statisticians ______ the outlier after confirming it was a decimal in the wrong place, not a new phenomenon." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "removed", B: "celebrated as theory", C: "sold", D: "sang" }, answer: "A", explain: { correct: "Removed the outlier after it proved to be a decimal error is correct cleaning.", wrong: { B: "A wrong decimal is not a new theory to celebrate.", C: "Sold is commercial.", D: "Sang is unrelated." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A “neutral” news photo is still taken from somewhere. Height, distance, and who is in focus are choices. Neutrality, if it exists, is a pile of those choices that we have stopped noticing." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To treat photographic neutrality as a set of unnoticed decisions", B: "To sell lenses", C: "To deny that photos can be published", D: "To teach focus as a medical term only" }, answer: "A", explain: { correct: "Somewhere, height/distance/focus, neutrality as unnoticed choices.", wrong: { B: "No product is sold.", C: "Photos are assumed publishable.", D: "Focus is optical/editorial." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "When a study is “the first to,” check the languages of the bibliography. First in English is not first on Earth." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It specifies what “first” often actually means in practice", B: "It lists languages", C: "It bans English papers", D: "It defines Earth in astronomy" }, answer: "A", explain: { correct: "First in English versus first on Earth narrows the boast.", wrong: { B: "No language list appears.", C: "English papers are to be read more humbly, not banned.", D: "Earth means worldwide scholarship." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Ask who filed the complaint. Ask who could afford the lawyer. Ask who never filed. Courts see a filtered world." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "Three questions that justify a claim about courts’ limited view", B: "A lawyer advertisement", C: "A filter as a coffee guide", D: "A world atlas" }, answer: "A", explain: { correct: "Filer, lawyer money, non-filers, then filtered world.", wrong: { B: "Not an ad.", C: "Filter is metaphorical.", D: "World means the social world courts see." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Daylight saving time should be abolished. The twice-yearly shift raises heart-attack rates and saves little energy in modern buildings." }, { label: "Text 2", body: "Abolishing the shift is right; locking the clock on permanent daylight saving is not the same as locking it on standard time. Evening light is not free. It is morning darkness moved onto school bus stops. Choose the lock, not only the abolition." }], prompt: "Both authors would most likely agree that", choices: { A: "the twice-yearly clock change is a problem worth ending", B: "heart attacks are unrelated to sleep", C: "school buses should run at midnight", D: "energy savings justify any shift" }, answer: "A", explain: { correct: "Text 1 wants the shift abolished; Text 2 says abolishing the shift is right, then debates which permanent setting.", wrong: { B: "Text 1 cites heart-attack rates.", C: "Text 2 worries about morning bus stops, not midnight buses.", D: "Text 1 says little energy is saved." } } }
  ]
},
{
  day: 36, date: "2026-10-24",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The harbor fog was so ______ that ferries ran on instruments and horns rather than on sight." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "dense", B: "absent", C: "decorative", D: "theoretical" }, answer: "A", explain: { correct: "Dense fog blocks sight, so instruments and horns fit.", wrong: { B: "Absent fog would allow sight.", C: "Decorative is unrelated.", D: "Ferries are responding to real fog." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "The city ______ the mural after neighbors showed it had been commissioned without the block’s consent." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "paused", B: "enlarged immediately", C: "set to music", D: "ignored the neighbors" }, answer: "A", explain: { correct: "Paused means stopped temporarily; consent problems would halt work.", wrong: { B: "Enlarging immediately would ignore the consent issue.", C: "Music is unrelated.", D: "They responded to neighbors, so they did not ignore them." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The introduction is ______ about what the book will not do, which is rarer, and more useful, than a list of triumphs." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "candid", B: "boastful", C: "silent", D: "rhymed" }, answer: "A", explain: { correct: "Candid means frank; stating what the book will not do is frank scoping.", wrong: { B: "Boastful would list triumphs, which the sentence contrasts.", C: "Stating limits is not silence.", D: "Rhymed is form." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Seagrass beds ______ young fish, offering cover that open sand does not." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "shelter", B: "expose to predators more", C: "ignore", D: "translate" }, answer: "A", explain: { correct: "Shelter means protect; cover versus open sand fits.", wrong: { B: "Cover would not expose more than sand.", C: "Beds are providing cover, not ignoring fish.", D: "Translate is language." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The slogan was ______, memorable and false, which is a dangerous combination in a public-health campaign." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "catchy", B: "unmemorable", C: "peer-reviewed", D: "silent" }, answer: "A", explain: { correct: "Catchy means memorable; memorable-and-false is the danger named.", wrong: { B: "Unmemorable contradicts memorable.", C: "False slogans are not peer-reviewed science.", D: "A slogan that is memorable is not silent." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Two observatories ______ the same flicker in the star’s light, which made an instrument glitch less likely." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "recorded", B: "hid", C: "composed", D: "sold" }, answer: "A", explain: { correct: "Recorded the same flicker independently reduces glitch likelihood.", wrong: { B: "Hiding data would not confirm the flicker.", C: "Composed suggests making it up.", D: "Sold is commercial." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A “smart” irrigation system that waters by the calendar, not by soil moisture, is only a clock with a hose. Intelligence, here, would be a sensor, not a schedule sold as a sensor." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To distinguish genuine soil-based control from a marketed schedule", B: "To sell hoses", C: "To deny that plants need water", D: "To teach calendars" }, answer: "A", explain: { correct: "Calendar versus moisture, clock with a hose, sensor versus schedule sold as sensor.", wrong: { B: "Hose is part of the metaphor.", C: "Watering is assumed needed.", D: "Calendars are the inadequate method." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "A blurb that names three famous friends and no sentence from the book is an endorsement of a social circle. Read a page anyway." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It advises readers not to substitute blurbs for the text", B: "It lists the friends", C: "It bans blurbs", D: "It defines circles in geometry" }, answer: "A", explain: { correct: "Read a page anyway means do not let the social blurb replace the book.", wrong: { B: "No names appear.", C: "Blurbs are critiqued, not banned.", D: "Circle is social." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Copy the chart. Cover the title. Guess the claim. Then uncover the title and see whether you were led by the ink or by the caption." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "A procedure for testing whether a chart’s title is doing the arguing", B: "A guessing game with no purpose", C: "An ink as a chemistry lesson", D: "A caption contest for comedy" }, answer: "A", explain: { correct: "Copy, cover, guess, uncover—test ink versus caption.", wrong: { B: "The guess has a diagnostic purpose.", C: "Ink means the graphic.", D: "Not comedy." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Single-stair apartment buildings should be legal again. Extra stairs eat units, and many cities already have old single-stair buildings that have not burned down." }, { label: "Text 2", body: "Old buildings are not a complete fire lab. Smoke behavior, furnishings, and occupant mobility have changed. If single-stair returns, pair it with sprinklers, limited height, and a real inspection culture—not with nostalgia for a floor plan." }], prompt: "The author of Text 2 would most likely", choices: { A: "allow single-stair design only with modern fire mitigations, not as a nostalgia copy", B: "claim extra stairs never eat units", C: "deny that fires happen", D: "argue that inspections are useless" }, answer: "A", explain: { correct: "Text 2 lists sprinklers, height limits, and inspections if single-stair returns.", wrong: { B: "Text 1’s unit-count point is not Text 2’s target.", C: "Fire lab language assumes fires matter.", D: "Inspection culture is required." } } }
  ]
},
{
  day: 37, date: "2026-10-25",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The ice on the lake was ______, and the town posted warnings after a snowmobile broke through near the inlet." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "unreliable", B: "thick enough for a festival", C: "theoretical", D: "decorative" }, answer: "A", explain: { correct: "Unreliable ice that breaks under a snowmobile fits posted warnings.", wrong: { B: "Festival-thick ice would not break through.", C: "A real break-through is not theoretical.", D: "Decorative is unrelated." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Reporters ______ the agency’s timeline against 911 logs and found a twenty-minute gap." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "checked", B: "invented", C: "sang", D: "sold" }, answer: "A", explain: { correct: "Checked against logs is verification; a found gap fits.", wrong: { B: "Invented would not use 911 logs as a standard.", C: "Sang is unrelated.", D: "Sold is commercial." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The novel is ______ in its treatment of work, lingering on invoices and shift changes rather than on a single heroic night." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "unromantic", B: "melodramatic", C: "silent", D: "rhymed" }, answer: "A", explain: { correct: "Unromantic means not idealized; invoices and shifts versus a heroic night fit.", wrong: { B: "Melodrama would chase the heroic night.", C: "Lingering on invoices is not silence.", D: "Rhymed is form." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Reefs ______ wave energy before it hits the shore, which is why some villages fought to restore coral rather than pour higher seawalls first." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "dissipate", B: "increase", C: "ignore", D: "patent" }, answer: "A", explain: { correct: "Dissipate means spread out and weaken; reefs reducing wave energy fits.", wrong: { B: "Increase would argue for walls, not coral.", C: "Reefs are doing physical work.", D: "Patent is legal." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "Her praise was so ______ that the cast could not tell which scene had actually succeeded." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "undifferentiated", B: "precise", C: "hostile", D: "wordless" }, answer: "A", explain: { correct: "Undifferentiated means not making distinctions; praise that does not mark which scene worked fits.", wrong: { B: "Precise praise would identify the scene.", C: "Praise is not hostility.", D: "Praise that is given is not wordless." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "The team ______ recruitment after realizing the sample had too few rural clinics." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "reopened", B: "ended permanently without comment", C: "set to music", D: "translated into Latin" }, answer: "A", explain: { correct: "Reopened recruitment to fix an undercounted group fits.", wrong: { B: "They are trying to fix the sample, not end silently.", C: "Music is unrelated.", D: "Latin is irrelevant." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A monument lighting show can draw crowds and starve the night sky. Tourism that needs darkness elsewhere to stay special is borrowing someone else’s quiet. Ask who loses the stars." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To weigh spectacle against stolen darkness and ask who pays", B: "To sell lighting rigs", C: "To deny that stars exist", D: "To teach astronomy formulas" }, answer: "A", explain: { correct: "Crowds versus night sky, borrowing quiet, who loses the stars.", wrong: { B: "No rigs are sold.", C: "Stars are assumed.", D: "No formulas appear." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "“Further research is needed” can be a map. It can also be a shrug that protects a weak result. Demand the next measurement, not the phrase." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It tells readers what to require instead of accepting a stock phrase", B: "It lists studies", C: "It praises all shrugs", D: "It defines maps in geography class only" }, answer: "A", explain: { correct: "Demand the next measurement, not the phrase, is the instruction.", wrong: { B: "No list appears.", C: "Shrug is the bad use.", D: "Map is metaphorical." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Name the chemical. Name the factory. Name the creek. A spill is a geography, not an accident without an address." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "Three namings that redefine a spill as located and caused", B: "A chemistry quiz with no places", C: "A factory tour brochure", D: "An accident as a legal term only" }, answer: "A", explain: { correct: "Chemical, factory, creek, then geography not address-less accident.", wrong: { B: "Places are essential.", C: "Not a brochure.", D: "The point is geography of harm." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Public comments at zoning hearings should be first-come, first-served. Any other order lets insiders speak while parents are still parking." }, { label: "Text 2", body: "First-come rewards people with flexible afternoons. A lottery for speaking slots, with a hold for adjacent residents, is less polite and more representative. Parking is real; so is a room already filled by retirees at 2 p.m." }], prompt: "Which choice best describes the difference in fairness?", choices: { A: "Text 1 treats arrival order as fair; Text 2 treats it as biased toward flexible schedules", B: "Text 2 wants no public comment", C: "Text 1 bans adjacent residents", D: "Both ignore parking" }, answer: "A", explain: { correct: "Text 1 defends first-come against insiders; Text 2 says first-come is itself an insider advantage of time.", wrong: { B: "Text 2 still wants speaking slots.", C: "Text 1 worries about parents parking, not banning residents.", D: "Both mention parking." } } }
  ]
},
{
  day: 38, date: "2026-10-26",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The diplomat’s toast was ______, offering goodwill without any new concession on the border." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "ceremonial", B: "decisive", C: "illegal", D: "rhymed" }, answer: "A", explain: { correct: "Ceremonial means for form and ritual; goodwill without a concession fits ceremony.", wrong: { B: "Decisive would include a real concession.", C: "A toast is not a legal category here.", D: "Rhymed is form of verse." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Technicians ______ the telescope’s mirror after frost left a film that would have blurred the night’s images." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "cleaned", B: "shattered", C: "sold", D: "ignored" }, answer: "A", explain: { correct: "Cleaned the frost film to prevent blur is maintenance.", wrong: { B: "Shattering would end the night’s work worse.", C: "Sold is commercial.", D: "They acted on the film, so they did not ignore it." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The chapter is ______, restating the thesis four times with no new case." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "redundant", B: "economical", C: "silent", D: "illustrated only by music" }, answer: "A", explain: { correct: "Redundant means needlessly repeated; four restatements without a new case fit.", wrong: { B: "Economical writing would not repeat four times.", C: "Restating is not silence.", D: "Music is not indicated." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Mangroves ______ storm surge, a fact coastal planners cited when they blocked a marina that would have cut the roots." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "blunt", B: "amplify", C: "ignore", D: "translate" }, answer: "A", explain: { correct: "Blunt means weaken the force of; mangroves reducing surge fits blocking a marina.", wrong: { B: "Amplify would not justify protecting roots.", C: "Mangroves are doing physical work.", D: "Translate is language." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The comparison was ______: it lined up two unlike crises to force a single moral, and both crises deserved their own terms." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "forced", B: "organic", C: "unspoken", D: "mathematical" }, answer: "A", explain: { correct: "Forced means strained; lining up unlike crises for one moral fits.", wrong: { B: "Organic would mean the likeness arose naturally.", C: "The comparison was made, so not unspoken.", D: "Mathematical is not the ethical issue." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Authors ______ a data-availability statement after the journal made it mandatory." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "added", B: "banned", C: "sang", D: "hid behind" }, answer: "A", explain: { correct: "Added a statement once it was mandatory is compliance.", wrong: { B: "Banned would fight the mandate.", C: "Sang is unrelated.", D: "They supplied the statement, not hid behind it as evasion in this sentence." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A “green” bond is a loan with a story. Read the covenants, not the color of the cover. If the money can still fund a highway lane, the story is paint." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To tell readers to test green-bond claims against actual spending rules", B: "To sell paint", C: "To deny that loans exist", D: "To teach highway engineering" }, answer: "A", explain: { correct: "Loan with a story, covenants not cover, highway lane as paint.", wrong: { B: "Paint is a metaphor for empty coloring.", C: "Bonds are loans.", D: "A highway lane is a counterexample, not a how-to." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "An index entry that says “see other” and then dies is a broken promise. Cross-references should land." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It states the rule that the broken “see other” entry violated", B: "It lists other entries", C: "It praises all indexes", D: "It defines landing in aviation" }, answer: "A", explain: { correct: "Cross-references should land is the rule against dying “see other” pointers.", wrong: { B: "No list appears.", C: "This index fails.", D: "Land is metaphorical." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Start with the outlier. Ask if it is dirt on the lens, a rare true event, or the thing you should have been studying. Curiosity is a sorting hat." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "A starting point, three interpretations, then a metaphor for the sorting", B: "A lens-cleaning manual only", C: "A Harry Potter plot summary", D: "A dirt as a soil science paper" }, answer: "A", explain: { correct: "Outlier first, three options, sorting-hat metaphor.", wrong: { B: "Dirt on the lens is one option.", C: "Sorting hat is a borrowed metaphor, not a plot summary.", D: "Dirt means contamination of data." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Congestion pricing should apply to delivery vans as well as cars. A van blocking a bike lane imposes costs that a car in motion does not." }, { label: "Text 2", body: "Pricing vans without off-hour delivery windows and loading bays just moves the double-park into the next poorest street. Charge the congestion, and also build the curb where a van is supposed to be." }], prompt: "Text 2 would most likely", choices: { A: "accept a charge on vans but insist on physical loading space so the charge is not only punitive", B: "exempt all vans forever", C: "deny that bike lanes exist", D: "claim cars never move" }, answer: "A", explain: { correct: "Text 2 says charge the congestion and build the curb; both price and infrastructure.", wrong: { B: "Charge the congestion includes vans.", C: "Bike lanes are in Text 1; Text 2 discusses streets and curbs as real.", D: "Not the issue." } } }
  ]
},
{
  day: 39, date: "2026-10-27",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The archive’s catalog was ______, with three spellings of the same surname, so researchers missed files that sat two drawers away." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "inconsistent", B: "meticulous in every spelling", C: "empty", D: "rhymed" }, answer: "A", explain: { correct: "Inconsistent spellings causing missed nearby files fit a messy catalog.", wrong: { B: "Meticulous spelling would not produce three versions.", C: "Files exist two drawers away, so not empty.", D: "Rhymed is poetic." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Nurses ______ the protocol after two near-misses, adding a read-back of the dose." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "tightened", B: "abandoned all checks", C: "sang", D: "sold" }, answer: "A", explain: { correct: "Tightened means made stricter; adding a dose read-back after near-misses fits.", wrong: { B: "They added a check, not abandoned checks.", C: "Sang is unrelated.", D: "Sold is commercial." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The narrator’s ______ is the point: she notices wallpaper and misses the coup." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "myopia", B: "omniscience", C: "silence", D: "speed" }, answer: "A", explain: { correct: "Myopia means shortsightedness; wallpaper seen, coup missed, is limited vision as design.", wrong: { B: "Omniscience would catch the coup.", C: "Noticing wallpaper is not silence.", D: "Speed is not the noticing pattern." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Dunes ______ inland when vegetation was removed, burying the first row of cottages in a decade." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "migrated", B: "froze in place", C: "dissolved into law", D: "were painted" }, answer: "A", explain: { correct: "Migrated means moved; inland movement burying cottages fits.", wrong: { B: "Froze in place would not bury cottages.", C: "Law is unrelated.", D: "Painted is not movement." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The headline ______ the study, turning a modest correlation into a miracle cure." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "sensationalized", B: "understated", C: "copied word for word from the abstract’s caution", D: "ignored by not running" }, answer: "A", explain: { correct: "Sensationalized means hyped; modest correlation to miracle cure is hype.", wrong: { B: "Understated would shrink the claim.", C: "A caution in the abstract would not yield a miracle headline.", D: "The headline ran." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Two clocks were ______ to a common satellite signal so that the explosion’s origin could be timed." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "synchronized", B: "destroyed", C: "rhymed", D: "sold separately as art" }, answer: "A", explain: { correct: "Synchronized means set to the same time; a common satellite signal is how.", wrong: { B: "Destroyed clocks cannot time an origin.", C: "Rhymed is poetic.", D: "Art sales are irrelevant." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A “complete streets” project that paints a bike lane and leaves the door zone is a slogan on asphalt. Completeness is a buffer, not a color." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To criticize paint-only bike lanes that omit physical safety", B: "To sell paint", C: "To deny that streets exist", D: "To teach color theory" }, answer: "A", explain: { correct: "Paint versus door zone, slogan on asphalt, buffer not color.", wrong: { B: "Paint is the inadequate intervention.", C: "Streets are assumed.", D: "Color is metaphorical for paint." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "A footnote that cites “personal communication” is a door you cannot knock on. Use it sparingly. Readers cannot audit a conversation." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It explains why such citations should be rare", B: "It lists conversations", C: "It praises all unpublished talk", D: "It teaches knocking as etiquette only" }, answer: "A", explain: { correct: "Readers cannot audit a conversation is the reason to use personal communication sparingly.", wrong: { B: "No list appears.", C: "The stance is restrictive.", D: "Knock is metaphorical." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Take the official map. Overlay the flood. Overlay who got the sandbags first. Cartography plus logistics is the real civic picture." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "Two overlays on an official map, then a definition of the civic picture", B: "A sandbag as a product review", C: "A flood as a novel", D: "A logistics textbook chapter in full" }, answer: "A", explain: { correct: "Map, flood, sandbag order, then cartography plus logistics.", wrong: { B: "Not a product review.", C: "Not a novel.", D: "A principle, not a full textbook." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Standardized patients are better than lectures for teaching bad-news conversations. You cannot lecture someone through the silence after a diagnosis." }, { label: "Text 2", body: "Actors help, and they still say the same bad news on a schedule. Add clinic afternoons where the diagnosis is real and the silence is not timed. Pedagogy that never leaves the simulation lab teaches a play." }], prompt: "The author of Text 2 would most likely", choices: { A: "keep simulated conversations but refuse to treat them as a complete education", B: "ban all patient contact", C: "claim silence cannot be taught in any form", D: "argue that lectures beat all practice" }, answer: "A", explain: { correct: "Text 2 says actors help, then demands untimed real clinic silence so it is not only a play.", wrong: { B: "Clinic afternoons are added, not banned.", C: "Silence is to be met in clinic, so it is teachable there.", D: "Text 1 already prefers practice to lectures; Text 2 does not reverse to lectures winning." } } }
  ]
},
{
  day: 40, date: "2026-10-28",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The truce remained ______ as artillery stayed on the reverse slope, ready but not firing." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "provisional", B: "eternal", C: "irrelevant", D: "rhymed" }, answer: "A", explain: { correct: "Provisional means temporary and conditional; guns ready but not firing is a fragile, not final, peace.", wrong: { B: "Eternal would not depend on ready guns.", C: "A truce in force is not irrelevant.", D: "Rhymed is poetic." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Lab workers ______ the cultures at 37 degrees so that the bacteria would grow at body temperature." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "incubated", B: "froze solid", C: "discarded", D: "sang to" }, answer: "A", explain: { correct: "Incubated means kept at a controlled warm temperature for growth.", wrong: { B: "Freezing solid would not grow bacteria at body temperature.", C: "Discarded cultures would not be grown.", D: "Sang is unrelated." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The memoir ______ sentimentality, describing the funeral through the logistics of chairs rather than through tears." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "avoids", B: "wallows in", C: "sets to music only", D: "omits all scenes of" }, answer: "A", explain: { correct: "Avoids sentimentality by using chair logistics instead of tears.", wrong: { B: "Wallows would chase tears.", C: "Music is not indicated.", D: "The funeral is described, not omitted; the mode is unsentimental." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Invasive vines ______ the canopy, stealing light from trees that had defined the floodplain." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "smothered", B: "restored", C: "catalogued as crops", D: "ignored" }, answer: "A", explain: { correct: "Smothered means covered and suppressed; stealing light from canopy trees fits.", wrong: { B: "Restored would help the trees.", C: "Crops are not the claim.", D: "The vines are acting, not ignoring." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The author’s ______—a habit of saying “we now know” about disputed claims—irritated historians who still did not know." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "overconfidence", B: "humility", C: "silence", D: "precision" }, answer: "A", explain: { correct: "Overconfidence is excessive certainty; “we now know” on disputed claims fits.", wrong: { B: "Humility would not irritate that way.", C: "Saying “we now know” is not silence.", D: "Precision would mark dispute, not erase it." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Reviewers ______ a control group after noticing that the study had compared the drug only with doing nothing at a different hospital." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "demanded", B: "forbade", C: "composed", D: "photographed" }, answer: "A", explain: { correct: "Demanded a control group flags a design hole (different hospital, doing nothing).", wrong: { B: "Forbade would block the needed control.", C: "Composed is writing music or text, not requiring a design element.", D: "Photographed is irrelevant." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A “resilient” city brochure that never mentions power outages is selling a mood. Resilience is a generator test, a cooling center, and a list of who gets ice. Print the list." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To replace vague resilience talk with concrete preparedness measures", B: "To sell ice as a luxury brand", C: "To deny that outages happen", D: "To teach brochure design" }, answer: "A", explain: { correct: "Mood versus generator, cooling center, ice list—print the list.", wrong: { B: "Ice is a need, not a luxury ad.", C: "Outages are what brochures omit and should not.", D: "Design is not the lesson; content is." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "“It goes without saying” is a way of saying it while pretending you did not. If it went without saying, the sentence would be blank." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It exposes the contradiction in the quoted phrase", B: "It praises blank pages", C: "It lists things that go without saying", D: "It defines going as travel" }, answer: "A", explain: { correct: "If it went without saying, the sentence would be blank—contradicting the phrase’s use.", wrong: { B: "Blank is a test, not praise of empty books.", C: "No list appears.", D: "Going is part of the idiom." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Write the claim. Write the test. Write what would make you recant. A theory that cannot name its own death is a slogan." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "Three writing tasks that define a theory versus a slogan", B: "A death as a medical chart", C: "A slogan as an advertising course", D: "A recantation as a religious history" }, answer: "A", explain: { correct: "Claim, test, recant condition, then slogan if death cannot be named.", wrong: { B: "Death of a theory is metaphorical.", C: "Slogan is the failure mode.", D: "Recant means abandon the claim empirically." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Open educational resources should replace commercial textbooks. Students already pay tuition; a $200 book is a second tax on the same lecture." }, { label: "Text 2", body: "Free files that are outdated, unaccessible, or missing problem sets are not a replacement; they are a gap with a Creative Commons logo. Fund the updates, or the second tax simply moves onto printouts and confusion." }], prompt: "Both authors are concerned with", choices: { A: "whether students can get usable course materials without an unfair extra cost", B: "how to print logos", C: "whether tuition should triple", D: "only the history of paper mills" }, answer: "A", explain: { correct: "Text 1 hates the $200 extra tax; Text 2 says free-but-unusable still costs students. Shared issue: usable materials and cost.", wrong: { B: "Logo is Text 2’s jab at empty openness.", C: "Neither wants higher tuition as the point.", D: "Not paper mills." } } }
  ]
}
);
