window.SAT_DAYS = window.SAT_DAYS || [];
window.SAT_DAYS.push(
{
  day: 51, date: "2026-11-08",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The mountain pass was ______ after the slide, and buses were rerouted for a week." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "impassable", B: "newly paved", C: "theoretical", D: "decorative" }, answer: "A", explain: { correct: "Impassable means you cannot go through; a slide plus a week of reroutes fits.", wrong: { B: "Newly paved would not force reroutes after a slide.", C: "Buses were really rerouted.", D: "Decorative is unrelated." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Journalists ______ the press release against payroll records and found the job-creation number had been doubled." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "checked", B: "copied uncritically", C: "sang", D: "sold" }, answer: "A", explain: { correct: "Checked against payroll is verification; finding a doubled number fits.", wrong: { B: "Uncritical copying would not find the doubling.", C: "Sang is unrelated.", D: "Sold is commercial." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The essay is ______ in its compliments, which makes the one harsh paragraph more credible." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "sparing", B: "gushing", C: "silent", D: "rhymed" }, answer: "A", explain: { correct: "Sparing compliments make a harsh paragraph stand out as earned.", wrong: { B: "Gushing would drown the harsh paragraph in praise.", C: "Compliments exist, so not silent.", D: "Rhymed is form." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Wetlands ______ nitrogen from farm runoff, a service the county later tried to price." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "remove", B: "add extra", C: "ignore", D: "patent" }, answer: "A", explain: { correct: "Remove nitrogen is a water-quality service worth pricing.", wrong: { B: "Adding extra nitrogen would worsen runoff effects.", C: "The service is chemical work.", D: "Patent is legal." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The slogan ______ a staffing crisis as a “mindset issue,” which infuriated nurses on their third consecutive night shift." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "recast", B: "accurately measured", C: "set to an anthem", D: "ignored by not speaking" }, answer: "A", explain: { correct: "Recast means framed differently; crisis as mindset is a reframing nurses reject.", wrong: { B: "Mindset talk is not a measurement of staffing.", C: "Anthem is unrelated.", D: "A slogan speaks." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Two labs ______ the protein’s weight, which made a calibration error in one machine less likely." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "agreed on", B: "invented", C: "sang", D: "hid" }, answer: "A", explain: { correct: "Agreed on the weight across labs weakens a one-machine error story.", wrong: { B: "Invented would not be independent agreement.", C: "Sang is unrelated.", D: "Hiding would not confirm the weight." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A “complete streets” plan that paints symbols and leaves turning speeds unchanged is calligraphy. Completeness is a slower corner, not a stencil." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To insist that street safety is speed and design, not only painted symbols", B: "To sell stencils", C: "To deny that corners exist", D: "To teach calligraphy" }, answer: "A", explain: { correct: "Paint versus turning speeds, calligraphy, slower corner not stencil.", wrong: { B: "Stencil is the inadequate tool.", C: "Corners should be slower.", D: "Calligraphy is a metaphor for empty marking." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "“As we all know” tries to make you a member of a club that did not elect you. Resign. Ask for the citation." }], prompt: "Which choice best describes the function of the last two sentences?", choices: { A: "They instruct the reader to refuse fake consensus and demand a source", B: "They explain club elections", C: "They list citations", D: "They agree that everyone already knows" }, answer: "A", explain: { correct: "Resign and ask for the citation is refusal of “as we all know.”", wrong: { B: "Club is metaphorical.", C: "No list appears.", D: "They reject that claim." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "List the hazard. List the warning label. List who cannot read it. Safety literature that ignores literacy is incomplete literature." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "Three lists that expose a gap between warnings and who can use them", B: "A novel about literature class", C: "A hazard as a golf term", D: "A label as a fashion tag" }, answer: "A", explain: { correct: "Hazard, label, who cannot read, then incomplete safety literature.", wrong: { B: "Literature means written material.", C: "Hazard means danger.", D: "Warning label is safety, not fashion." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Congestion pricing should be a flat daily charge. Simplicity is what makes a policy survivable." }, { label: "Text 2", body: "A flat charge is simple and crude. It hits a nurse on a night shift the same as a midday shopper who could have taken a train. Simplicity that ignores schedules is not fairness. A peak-only charge is harder to explain and easier to defend." }], prompt: "Text 2 would most likely characterize Text 1’s simplicity as", choices: { A: "politically useful but unfair to people who cannot shift their trips", B: "the definition of fairness", C: "unrelated to charges", D: "a reason to abolish all trains" }, answer: "A", explain: { correct: "Text 2 grants that flat is simple, then says it hits nurses like optional shoppers; peak-only is fairer if harder.", wrong: { B: "Text 2 denies that equation.", C: "Both discuss congestion charges.", D: "Trains are an option for some shoppers in Text 2." } } }
  ]
},
{
  day: 52, date: "2026-11-09",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The river gauge was ______ during the flood, so officials used a painted bridge mark as a backup." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "offline", B: "perfectly precise", C: "theoretical", D: "decorative" }, answer: "A", explain: { correct: "Offline means not working; a painted mark as backup fits a dead gauge.", wrong: { B: "Perfect precision would not need a bridge mark.", C: "The flood was real.", D: "Decorative is unrelated." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "The city ______ the mural’s lighting after neighbors showed it shone into bedrooms." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "dimmed", B: "brightened further", C: "sang", D: "ignored" }, answer: "A", explain: { correct: "Dimmed lighting that shone into bedrooms is the neighbor-driven fix.", wrong: { B: "Brightening would worsen bedrooms.", C: "Sang is unrelated.", D: "They changed the lights, so they did not ignore neighbors." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The memoir ______ the father’s jokes, quoting them without the narrator’s protective wince." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "reproduces", B: "censors completely", C: "sets only to music", D: "omits from every chapter" }, answer: "A", explain: { correct: "Reproduces means quotes as they were; without a wince is unbuffered quotation.", wrong: { B: "Complete censorship would not quote them.", C: "Music is not indicated.", D: "Quoting is not omitting from every chapter." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Mangroves ______ young fish among their roots, which is why some marinas were blocked." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "shelter", B: "expose more than open water would", C: "ignore", D: "translate" }, answer: "A", explain: { correct: "Shelter among roots explains blocking marinas to keep nursery habitat.", wrong: { B: "Exposure would not justify blocking marinas for fish.", C: "Roots are doing habitat work.", D: "Translate is language." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The headline’s ______—“cure” for a modest correlation—drew a letter from the paper’s own authors." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "overstatement", B: "caution", C: "silence", D: "rhyme" }, answer: "A", explain: { correct: "Overstatement is “cure” for a modest correlation; authors writing in to object fits.", wrong: { B: "Caution would not say cure.", C: "A headline that says cure is not silence.", D: "Rhyme is verse." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Teams ______ their clocks to GPS so that the two seismic traces could be overlaid." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "locked", B: "destroyed", C: "sang", D: "sold" }, answer: "A", explain: { correct: "Locked to GPS means synchronized; overlaying traces requires that.", wrong: { B: "Destroyed clocks cannot overlay traces.", C: "Sang is unrelated.", D: "Sold is commercial." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A “green” roof that is never watered is a drought in midair. Maintenance is the plant, not the press photo on installation day." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To treat green roofs as living systems that fail without upkeep", B: "To sell press photos", C: "To deny that roofs exist", D: "To teach drought as a climate textbook in full" }, answer: "A", explain: { correct: "Never watered, drought in midair, maintenance not installation photo.", wrong: { B: "Photo is the empty substitute.", C: "Roofs are assumed.", D: "Drought is a metaphor for a dead roof garden." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "A footnote that says “emphasis in original” is a courtesy. A footnote that adds emphasis and omits that fact is a ventriloquist act." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It names a dishonest opposite of the courtesy just described", B: "It teaches ventriloquism", C: "It lists footnotes", D: "It praises all added italics" }, answer: "A", explain: { correct: "Adding emphasis while omitting the fact is ventriloquism, the dishonest counterpart.", wrong: { B: "Ventriloquist is metaphorical.", C: "No list appears.", D: "Added italics without disclosure are criticized." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Ask who cleaned the lab. Ask who is in the author list. Ask whose name is in the acknowledgment as “technical help.” Credit is a caste system if you do not look." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "Three questions that reveal unequal credit, then a generalization", B: "A caste as a South Asian history textbook in full", C: "A lab as a dog-cleaning service", D: "An author list as a phone book" }, answer: "A", explain: { correct: "Cleaner, authors, technical help, then caste if you do not look.", wrong: { B: "Caste is a metaphor for hierarchy.", C: "Cleaned the lab means research labor.", D: "Author list is scholarly credit." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "School phone bans should be total. Partial bans become a negotiation every period." }, { label: "Text 2", body: "A total ban that ignores medical apps and IEP accommodations will be struck, and should be. Default off, documented exceptions, and a lockable pouch are a policy. Theater of confiscation is not." }], prompt: "Both authors are trying to solve", choices: { A: "how phones should be governed during the school day", B: "how to manufacture pouches", C: "whether schools should close", D: "only cafeteria seating" }, answer: "A", explain: { correct: "Text 1 wants a total ban; Text 2 wants default-off plus exceptions. Shared problem: phone rules.", wrong: { B: "Pouch is one tool in Text 2.", C: "School days continue.", D: "Not seating." } } }
  ]
},
{
  day: 53, date: "2026-11-10",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The trail markers were ______ by new growth, and hikers missed the turn to water." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "obscured", B: "repainted brighter", C: "theoretical", D: "musical" }, answer: "A", explain: { correct: "Obscured by growth explains missing the water turn.", wrong: { B: "Brighter paint would not hide the turn.", C: "Hikers missed a real turn.", D: "Musical is unrelated." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "The council ______ the ordinance after a court suggested it was too vague to enforce." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "rewrote", B: "left untouched", C: "sang", D: "sold" }, answer: "A", explain: { correct: "Rewrote after a vagueness warning is a legal fix.", wrong: { B: "Untouched would keep the vagueness problem.", C: "Sang is unrelated.", D: "Sold is commercial." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The critic’s ______—granting the novel’s sentences and rejecting its ethics—felt more adult than a total dismissal." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "split judgment", B: "unconditional rave", C: "silence", D: "plot summary only" }, answer: "A", explain: { correct: "Split judgment grants sentences and rejects ethics.", wrong: { B: "A rave would not reject ethics.", C: "Granting and rejecting is not silence.", D: "The move is evaluative, not mere plot." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Beavers ______ summer streamflow by storing water in ponds that leak slowly in August." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "sustained", B: "eliminated", C: "ignored", D: "patented" }, answer: "A", explain: { correct: "Sustained flow via slow-leaking ponds is a drought buffer.", wrong: { B: "Eliminated flow would dry August.", C: "Beavers are changing hydrology.", D: "Patent is legal." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The metaphor ______ a company as a family, which made firing sound like a quarrel instead of a power relation." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "cast", B: "refused to describe", C: "rhymed", D: "unspoke" }, answer: "A", explain: { correct: "Cast as means portrayed as; family-metaphor softening firing fits.", wrong: { B: "The metaphor did describe the company that way.", C: "Rhymed is verse.", D: "Unspoke is not standard here; the metaphor was used." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Authors ______ a correction when a reader found that a graph’s axis had been truncated." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "issued", B: "denied by silence forever", C: "sang", D: "sold" }, answer: "A", explain: { correct: "Issued a correction after a truncated axis was found.", wrong: { B: "They corrected, so not forever silent.", C: "Sang is unrelated.", D: "Sold is commercial." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A “vision zero” target without a speed-limit change is a wish. Zero is an engineering problem. Wishes do not shorten stopping distance." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To insist that a fatality target requires physical speed policy, not only aspiration", B: "To sell wishes", C: "To deny that stopping distance exists", D: "To teach engineering calculus in full" }, answer: "A", explain: { correct: "No speed change, wish, engineering, stopping distance.", wrong: { B: "Wishes are insufficient.", C: "Stopping distance is the physics named.", D: "Not a full calculus course." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "“Further studies are warranted” can be a map of the next measurement. It can also be a polite way to leave town. Demand the measurement." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It tells readers what to require instead of accepting a polite exit", B: "It lists studies", C: "It praises leaving town", D: "It defines maps as road atlases only" }, answer: "A", explain: { correct: "Demand the measurement rejects the polite-exit use of the phrase.", wrong: { B: "No list appears.", C: "Leaving town is the bad use.", D: "Map is metaphorical." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Name the chemical. Name the pipe. Name the school downstream. Abstraction is how a spill becomes nobody’s child." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "Three namings that accuse abstraction of erasing victims", B: "A chemistry exam with no places", C: "A pipe as plumbing shopping", D: "A school as a sports recap" }, answer: "A", explain: { correct: "Chemical, pipe, school, then nobody’s child.", wrong: { B: "Places are the point.", C: "Pipe is the source.", D: "School is the downstream community." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Public broadband should be a utility. Private underinvestment in poor blocks is a market outcome, not a mystery." }, { label: "Text 2", body: "Utility status can finance those blocks and can also freeze a clumsy municipal vendor in place for twenty years. Pair public money with an operator that publishes uptime, or the utility is a slower kind of neglect." }], prompt: "Text 2 would most likely", choices: { A: "support reaching underserved blocks but require operational accountability, not only public branding", B: "deny that poor blocks exist", C: "claim uptime does not matter", D: "argue that markets never underinvest" }, answer: "A", explain: { correct: "Text 2 says utility status can finance those blocks, then demands published uptime.", wrong: { B: "Those blocks are the financing target.", C: "Uptime is required.", D: "Text 1’s underinvestment point is not denied; execution is added." } } }
  ]
},
{
  day: 54, date: "2026-11-11",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The ice was ______ near the inlet, where current kept a dark patch open even in January." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "thin", B: "uniformly thick", C: "theoretical", D: "decorative" }, answer: "A", explain: { correct: "Thin ice near current, dark patch open, is a known hazard.", wrong: { B: "Uniform thickness would not leave an open patch.", C: "January current is real.", D: "Decorative is unrelated." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Reporters ______ the unnamed leak after two documents with the same odd phrase appeared in a public docket." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "corroborated", B: "invented", C: "sang", D: "sold" }, answer: "A", explain: { correct: "Corroborated means backed up; matching odd phrases in a docket support the leak.", wrong: { B: "Invented would not match a public docket.", C: "Sang is unrelated.", D: "Sold is commercial." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The novel’s politics arrive ______, through who is allowed to finish a sentence." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "obliquely", B: "in a manifesto chapter", C: "not at all", D: "only as rhyme" }, answer: "A", explain: { correct: "Obliquely means indirectly; who finishes sentences is an indirect political signal.", wrong: { B: "A manifesto would be direct.", C: "Politics that arrive somehow do arrive.", D: "Rhyme is not the vehicle named." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Dunes ______ cottages after vegetation was stripped for a view, a cost that arrived as sand in the beds." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "overran", B: "protected", C: "ignored", D: "translated" }, answer: "A", explain: { correct: "Overran means spread over; sand in beds after stripped vegetation fits.", wrong: { B: "Protected cottages would not fill with sand.", C: "Dunes are acting on cottages.", D: "Translate is language." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The author’s ______ of “we”—for a team of two writing about millions—drew complaints about scale." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "casual", B: "carefully limited", C: "silent", D: "numerical" }, answer: "A", explain: { correct: "Casual “we” covering millions from a team of two is a scale problem.", wrong: { B: "Carefully limited we would not draw scale complaints.", C: "Using “we” is not silence.", D: "We is a pronoun, not a number." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "The committee ______ recruitment to a second clinic so that the sample would not be a single hallway." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "extended", B: "ended", C: "sang", D: "sold" }, answer: "A", explain: { correct: "Extended recruitment to a second clinic diversifies beyond one hallway.", wrong: { B: "Ended recruitment would not add a clinic.", C: "Sang is unrelated.", D: "Sold is commercial." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A “historic district” that freezes paint colors and not wages will keep a look for visitors. History as a backdrop is not the same as history as a living wage behind the shutters." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To contrast visitor-facing appearance rules with the economic life of residents", B: "To sell paint", C: "To deny that shutters exist", D: "To teach wage law in full" }, answer: "A", explain: { correct: "Paint versus wages, look for visitors, backdrop versus living wage.", wrong: { B: "Paint is the surface rule.", C: "Shutters are assumed.", D: "Not a full labor-law course." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "“Standard methods” unnamed are a locked drawer. Name the method or say you want trust without a key." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It forces authors to choose specificity or an honest request for trust", B: "It lists methods", C: "It praises locked drawers", D: "It defines keys in locksmithing" }, answer: "A", explain: { correct: "Name it or ask for trust without a key is the choice.", wrong: { B: "No list appears.", C: "Locked drawer is the problem.", D: "Key is metaphorical." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Plot the ticket. Plot the neighborhood. Plot who never got one for the same turn. A ticket is a story about attention." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "Three plots that recast tickets as selective attention", B: "A ticket as a concert stub only", C: "A turn as a dance lesson", D: "A story as a fiction MFA ad" }, answer: "A", explain: { correct: "Ticket, neighborhood, who never got one, then attention story.", wrong: { B: "Ticket means citation.", C: "Turn means driving maneuver.", D: "Story means account, not a degree ad." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Library fines should return. Without them, due dates become suggestions and new releases vanish for months." }, { label: "Text 2", body: "Fines punish poverty more than forgetfulness. Automatic renewals, texts, and a replacement fee only for lost items can protect the catalog without a late tax on the people who need the library most." }], prompt: "Which choice best describes the shared goal and the split?", choices: { A: "Both care about shared collections remaining available; they disagree on whether fines are the right tool", B: "Text 2 wants books never returned", C: "Text 1 wants libraries closed", D: "Both ignore due dates" }, answer: "A", explain: { correct: "Text 1 fears vanished new releases; Text 2 still wants to protect the catalog, via renewals and texts not fines.", wrong: { B: "Replacement fees for lost items still exist in Text 2.", C: "Text 1 wants the catalog circulating.", D: "Due dates are central to both." } } }
  ]
},
{
  day: 55, date: "2026-11-12",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The ferry was ______ for two hours in fog, and cars backed up onto the two-lane road." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "delayed", B: "ahead of schedule", C: "theoretical", D: "decorative" }, answer: "A", explain: { correct: "Delayed in fog with a car backup fits.", wrong: { B: "Ahead of schedule would not back up cars.", C: "The fog delay is real.", D: "Decorative is unrelated." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Editors ______ a box around the limitation so that skimmers could not miss it." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "put", B: "removed all mention of", C: "sang", D: "sold" }, answer: "A", explain: { correct: "Put a box around the limitation to stop skimmers missing it.", wrong: { B: "Removing mention would hide it more.", C: "Sang is unrelated.", D: "Sold is commercial." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The play is ______ about work, lingering on punch clocks rather than on a single heroic overtime night." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "unsentimental", B: "melodramatic", C: "silent", D: "rhymed" }, answer: "A", explain: { correct: "Unsentimental means not gauzy; punch clocks versus heroic overtime fit.", wrong: { B: "Melodrama would chase the heroic night.", C: "Lingering on clocks is not silence.", D: "Rhymed is form." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Oysters ______ the creek’s clarity by filtering algae, which kayak guides later used as a selling point." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "improved", B: "worsened", C: "ignored", D: "translated" }, answer: "A", explain: { correct: "Improved clarity by filtering algae; guides selling that service fits.", wrong: { B: "Filtering algae would not worsen clarity.", C: "Oysters are doing the filtering.", D: "Translate is language." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The analogy ______ when it treated attention as a fuel, because attention does not sit in a tank you can fill overnight." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "failed", B: "became perfect", C: "went unspoken", D: "rhymed" }, answer: "A", explain: { correct: "Failed because attention is not a tank of fuel you refill overnight.", wrong: { B: "Perfect would mean the likeness held.", C: "The analogy was used.", D: "Rhyme is not the issue." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Labs ______ the odd reading by swapping sensors, then kept the reading when it survived the swap." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "tested", B: "discarded immediately", C: "sang", D: "sold" }, answer: "A", explain: { correct: "Tested by swapping sensors; keeping it after survival is confirmation.", wrong: { B: "They kept it, so they did not discard immediately.", C: "Sang is unrelated.", D: "Sold is commercial." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A “smart” thermostat demo that never shows the privacy menu is a sales script. Intelligence that maps your absences is a product with two faces. Turn the box around." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To pair convenience marketing with a demand to inspect privacy settings", B: "To sell thermostats uncritically", C: "To deny that absences can be mapped", D: "To teach boxing as a sport" }, answer: "A", explain: { correct: "No privacy menu, two faces, turn the box around.", wrong: { B: "Sales script is criticized.", C: "Mapping absences is the second face.", D: "Box means the device." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "A blurb that is only famous names is a guest list. Read a page of the book. Parties are not arguments." }], prompt: "Which choice best describes the function of the last two sentences?", choices: { A: "They tell readers not to confuse social proof with the text’s argument", B: "They list guests", C: "They ban blurbs", D: "They define parties in law" }, answer: "A", explain: { correct: "Read a page; parties are not arguments.", wrong: { B: "No list appears.", C: "Blurbs are to be overridden by reading, not banned.", D: "Parties means social gatherings." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Cover the caption. Guess the claim from the bars. Uncover the caption. See who was doing the arguing." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "A blinding exercise that tests whether a chart or its caption carries the claim", B: "A bar as a tavern review", C: "A caption contest for comedy", D: "An argument as a courtroom TV guide" }, answer: "A", explain: { correct: "Cover, guess, uncover, who was arguing.", wrong: { B: "Bars mean chart bars.", C: "Not comedy.", D: "Arguing means making the claim." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Single-stair housing should return so that small lots can yield more homes." }, { label: "Text 2", body: "More homes on small lots is the right goal. Smoke, furnishings, and mobility have changed since the old code. If single-stair returns, cap the height, require sprinklers, and inspect. A floor plan is not a fire study." }], prompt: "The author of Text 2 would most likely", choices: { A: "accept the housing goal and condition single-stair on modern fire mitigations", B: "reject any increase in homes", C: "claim smoke no longer exists", D: "argue that inspections are theater only" }, answer: "A", explain: { correct: "Right goal, then height cap, sprinklers, inspect—not nostalgia for a plan.", wrong: { B: "More homes is accepted.", C: "Smoke is why mitigations exist.", D: "Inspect is required as real, not theater." } } }
  ]
},
{
  day: 56, date: "2026-11-13",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The snowmobile trail was ______ by noon melt, and clubs posted a dawn-only warning." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "weakened", B: "hardened further", C: "theoretical", D: "decorative" }, answer: "A", explain: { correct: "Weakened by noon melt explains a dawn-only warning.", wrong: { B: "Hardening would allow midday travel.", C: "Melt is real.", D: "Decorative is unrelated." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "The museum ______ “discovered” to “collected,” a one-word change that shifted the story of power." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "changed", B: "kept forever", C: "sang", D: "sold" }, answer: "A", explain: { correct: "Changed discovered to collected is the one-word power shift.", wrong: { B: "Kept forever would not be a change.", C: "Sang is unrelated.", D: "Sold is commercial." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The biography is ______ of souvenir stories, dating each one to its first appearance in print." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "suspicious", B: "enamored", C: "silent", D: "rhymed" }, answer: "A", explain: { correct: "Suspicious of souvenir stories means it tests them by first-print dates.", wrong: { B: "Enamored would repeat them undated.", C: "Dating stories is not silence.", D: "Rhymed is form." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Otters ______ kelp by eating urchins, a chain later visible in aerial surveys." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "released", B: "destroyed as a goal", C: "ignored", D: "translated" }, answer: "A", explain: { correct: "Released kelp (from grazing pressure) by eating urchins; aerial surveys see the chain.", wrong: { B: "The goal is kelp return, not destruction.", C: "The chain is causal, not ignoring.", D: "Translate is language." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The slogan ______ years of staffing into “simply implement,” which is how plans die in the first week." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "flattened", B: "itemized honestly", C: "set to music", D: "ignored by remaining unsaid" }, answer: "A", explain: { correct: "Flattened staffing years into “simply implement” is oversimplification that kills plans.", wrong: { B: "Honest itemizing would keep the years visible.", C: "Music is unrelated.", D: "The slogan says the phrase." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Reviewers ______ raw files when a published figure looked airbrushed." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "asked for", B: "forbade", C: "sang", D: "sold" }, answer: "A", explain: { correct: "Asked for raw files to check an airbrushed look.", wrong: { B: "They want more evidence, not a ban on files.", C: "Sang is unrelated.", D: "Sold is commercial." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A “complete streets” ceremony that leaves the last driveway without a ramp is a photo of completeness. Completeness is the last driveway." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To locate completeness in leftover barriers, not in ceremonies", B: "To sell ramps as a brand", C: "To deny that driveways exist", D: "To teach photography" }, answer: "A", explain: { correct: "Ceremony versus last driveway without a ramp; completeness is that driveway.", wrong: { B: "Ramp is a needed feature, not an ad.", C: "Driveways are the test.", D: "Photo is empty optics." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "“As I have shown” in the introduction is a promise. The showing, if it happens, is the rest of the book." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It postpones proof from the introduction to the body", B: "It lists chapters", C: "It praises all introductions", D: "It defines showing as television" }, answer: "A", explain: { correct: "The rest of the book is where showing would happen.", wrong: { B: "No list appears.", C: "Early “shown” is treated as premature.", D: "Showing means demonstrating." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Name the leak. Name the valve. Name the creek. A spill is an address, not a mood." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "Three namings that insist a spill is located and mechanical", B: "A mood as a psychology quiz", C: "A valve as a heart anatomy lesson", D: "A creek as a travel ad" }, answer: "A", explain: { correct: "Leak, valve, creek, then address not mood.", wrong: { B: "Mood is the false frame.", C: "Valve means industrial valve.", D: "Creek is the receiving water." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Open offices should be replaced with assigned rooms. Measured focus collapses in noise." }, { label: "Text 2", body: "Assigned rooms help focus and can strand new hires in empty wings. A default quiet room plus bookable collision space treats interruption as a choice. The error was making noise the floor plan." }], prompt: "The author of Text 2 would most likely", choices: { A: "protect focus as default while keeping optional shared space", B: "defend noise as the goal", C: "claim focus does not matter", D: "ban all rooms" }, answer: "A", explain: { correct: "Default quiet plus bookable collision; interruption as choice, not architecture.", wrong: { B: "Noise as floor plan is the error.", C: "Quiet default means focus matters.", D: "Rooms are the tools." } } }
  ]
},
{
  day: 57, date: "2026-11-14",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The channel was ______ at low tide, and captains waited for slack water." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "shoal", B: "deeper than charts", C: "theoretical", D: "decorative" }, answer: "A", explain: { correct: "Shoal means shallow; waiting for slack at low tide fits a thin channel. \"Shoal\" as adjective means shallow.", wrong: { B: "Deeper than charts would not force waiting.", C: "Captains wait on real water.", D: "Decorative is unrelated." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "The board ______ comment to a two-minute cap, which turned stories into slogans." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "limited", B: "extended without end", C: "sang", D: "canceled the topic" }, answer: "A", explain: { correct: "Limited to two minutes flattening stories is a cap.", wrong: { B: "No end would not create slogans from shortness.", C: "Sang is unrelated.", D: "The topic still had comment, just capped." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The memoir ______ receipts the way other books treat love scenes: as the real plot." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "treats", B: "deletes all", C: "sets only to music", D: "ignores" }, answer: "A", explain: { correct: "Treats receipts as plot, analogous to love scenes in other books.", wrong: { B: "Deleting would not make them the plot.", C: "Music is not indicated.", D: "Treating as plot is not ignoring." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Invasive vines ______ light from the floodplain trees, a theft visible in the thinning canopy." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "stole", B: "added extra", C: "ignored", D: "patented" }, answer: "A", explain: { correct: "Stole light; thinning canopy is the visible theft.", wrong: { B: "Adding light would not thin the canopy.", C: "Theft is an action, not ignoring.", D: "Patent is legal." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The author’s ______—“obviously”—attached to a still-disputed claim, did not make the claim obvious." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "tic", B: "proof", C: "silence", D: "table" }, answer: "A", explain: { correct: "Tic means habitual verbal gesture; “obviously” on a disputed claim is a tic, not proof.", wrong: { B: "Proof would settle the dispute.", C: "Saying obviously is not silence.", D: "Table is not the word “obviously.”" } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Clinicians ______ a second site when one hospital’s patients were crowding the sample." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "added", B: "closed", C: "sang", D: "sold" }, answer: "A", explain: { correct: "Added a second site to uncrowd the sample.", wrong: { B: "Closed would worsen a one-hospital sample.", C: "Sang is unrelated.", D: "Sold is commercial." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A historic tax credit that polishes brick and raises rent is not a neighborhood policy. It is a postcard factory with a rebate." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To recast some preservation credits as visitor-facing transfers that lift rent", B: "To sell postcards", C: "To deny that brick can be polished", D: "To teach rebates as a math course" }, answer: "A", explain: { correct: "Polish and raise rent, not neighborhood policy, postcard factory with rebate.", wrong: { B: "Postcard is the insult.", C: "Polishing happens; rent is the issue.", D: "Not a math course." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "“Standard procedures were followed” without names is a vault. Give the combination or admit you are asking for faith." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It demands either a named method or an honest request for faith", B: "It lists procedures", C: "It praises vaults", D: "It defines faith in theology only" }, answer: "A", explain: { correct: "Combination or faith is the choice after the unnamed-procedures vault.", wrong: { B: "No list appears.", C: "Vault is the problem.", D: "Faith means trust in methods." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Plot the fine. Plot the block. Plot the unfined twin act. Power is the difference." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "Three plots that define power as unequal enforcement", B: "A twin as a biology lesson", C: "A block as a toy", D: "A difference as a subtraction worksheet only" }, answer: "A", explain: { correct: "Fine, block, unfined twin, then power as the difference.", wrong: { B: "Twin act means the same behavior.", C: "Block means neighborhood.", D: "Difference is political, not only arithmetic drill." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Two-minute public comment maximizes the number of speakers." }, { label: "Text 2", body: "Maximizing speakers can minimize hearing. A lottery of fewer, longer slots plus a written record that staff must answer beats a sloganeering line. Democracy is not a headcount of microphones." }], prompt: "Text 2 would most likely say Text 1 confuses", choices: { A: "more speakers with better listening", B: "lotteries with silence", C: "writing with microphones that cannot exist", D: "staff with speakers only in sports" }, answer: "A", explain: { correct: "Text 2 says maximizing speakers can minimize hearing; democracy is not microphone headcount.", wrong: { B: "Text 2 uses a lottery for longer slots.", C: "Written records are added, not impossible mics.", D: "Not sports." } } }
  ]
},
{
  day: 58, date: "2026-11-15",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The clinic fridge was ______ after the outage, and nurses moved vaccines into coolers with ice packs." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "warm", B: "colder than specifications", C: "theoretical", D: "decorative" }, answer: "A", explain: { correct: "Warm after an outage explains moving vaccines to ice packs.", wrong: { B: "Colder than spec would not require ice-pack rescue as warming.", C: "The outage was real.", D: "Decorative is unrelated." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Editors ______ the correction beside the original claim, so the file would not split the truth across issues." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "ran", B: "delayed a year", C: "sang", D: "sold" }, answer: "A", explain: { correct: "Ran the correction beside the claim keeps truth in one file/issue.", wrong: { B: "A year delay would split across issues.", C: "Sang is unrelated.", D: "Sold is commercial." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The narrator ______ her own charm until it becomes a tic the reader distrusts." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "advertises", B: "hides completely", C: "omits from the book", D: "sings" }, answer: "A", explain: { correct: "Advertises her charm until it is a tic readers distrust.", wrong: { B: "Hiding completely would not produce a visible tic.", C: "The charm is in the book as a tic.", D: "Sings is unrelated." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Reefs ______ wave force before seawalls, which is why coral restoration was budgeted as infrastructure." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "reduce", B: "increase", C: "ignore", D: "translate" }, answer: "A", explain: { correct: "Reduce wave force; infrastructure budget follows.", wrong: { B: "Increase would not justify coral as infrastructure.", C: "Reefs are doing physical work.", D: "Translate is language." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The household-budget analogy was ______ for a currency-issuing government, because households cannot issue bonds the same way." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "inapposite", B: "perfect", C: "unspoken", D: "musical" }, answer: "A", explain: { correct: "Inapposite means unfit; different bond-issuing power is the mismatch.", wrong: { B: "Perfect would require the same powers.", C: "The analogy was used.", D: "Musical is unrelated." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Researchers ______ a preregistered plan after critics said their paths looked like fishing." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "posted", B: "burned", C: "sang", D: "hid" }, answer: "A", explain: { correct: "Posted a preregistered plan to answer fishing criticisms.", wrong: { B: "Burned would not answer critics with a plan.", C: "Sang is unrelated.", D: "Hiding would worsen the fishing look." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "A walkability score that skips night lighting praises a street you cannot see. Walkability is 9 p.m. on a Tuesday." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To define walkability as after-dark usability, not a noon checklist", B: "To sell lights", C: "To deny that people walk at noon", D: "To teach scoring as gymnastics" }, answer: "A", explain: { correct: "Skip lighting, street you cannot see, 9 p.m. Tuesday.", wrong: { B: "Lighting is a condition.", C: "Noon audits are incomplete, not false.", D: "Score means an index." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "“Beyond the scope” can be an honest fence. It can also be a hole with a polite name. Ask whether the hole is load-bearing." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It tells readers to test whether an excluded issue actually matters to the claim", B: "It lists scopes", C: "It praises all holes", D: "It defines fences in carpentry only" }, answer: "A", explain: { correct: "Load-bearing hole means the exclusion might undermine the claim.", wrong: { B: "No list appears.", C: "Holes may be evasions.", D: "Fence and load-bearing are metaphorical." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Take the official count. Subtract doubles. Add the never-knocked. The census lives in that arithmetic." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "Two corrections to an official count, then a definition of the census", B: "A knock as a joke-telling guide", C: "A double as a baseball recap", D: "Arithmetic as a full algebra textbook" }, answer: "A", explain: { correct: "Count, subtract doubles, add never-knocked, census in that arithmetic.", wrong: { B: "Knocked means visited.", C: "Doubles mean double-counted people.", D: "A small arithmetic, not a textbook." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Admissions tests should remain because grades inflate unevenly." }, { label: "Text 2", body: "Inflation is real. A test that tracks wealth as tightly as it tracks math is not a clean substitute thermometer. Contextualize the test or drop it and read courses harder. Neutrality is the fairy tale." }], prompt: "The author of Text 2 would most likely", choices: { A: "accept uneven inflation but deny that the test is a neutral skill measure", B: "claim grades never inflate", C: "argue that math does not exist", D: "insist fairy tales should be admissions criteria" }, answer: "A", explain: { correct: "Inflation is real (grant) plus wealth-tracking (so not neutral); contextualize or drop.", wrong: { B: "Inflation is granted.", C: "Math is a tracked skill.", D: "Fairy tale is the insult to neutrality claims." } } }
  ]
},
{
  day: 59, date: "2026-11-16",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The pass was ______ until plows finished, and trucks stacked up at the lower lot." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "closed", B: "open to all loads", C: "theoretical", D: "decorative" }, answer: "A", explain: { correct: "Closed until plows finished, trucks stacked, fits a shutdown.", wrong: { B: "Open to all loads would not stack trucks.", C: "Plows are real.", D: "Decorative is unrelated." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "Journalists ______ job claims against unemployment filings and found a gap." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "tested", B: "repeated uncritically", C: "sang", D: "sold" }, answer: "A", explain: { correct: "Tested claims against filings; a gap is the finding.", wrong: { B: "Uncritical repetition would miss the gap.", C: "Sang is unrelated.", D: "Sold is commercial." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The essay’s compliments are ______, so the rebuke, when it comes, is believed." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "rare", B: "constant", C: "silent", D: "rhymed" }, answer: "A", explain: { correct: "Rare compliments make a later rebuke more credible.", wrong: { B: "Constant compliments would dilute a rebuke.", C: "Compliments exist, so not silent.", D: "Rhymed is form." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Wetlands ______ floodwater, spreading it so that downstream peaks fall." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "store", B: "shoot downstream instantly", C: "ignore", D: "patent" }, answer: "A", explain: { correct: "Store and spread floodwater to cut downstream peaks.", wrong: { B: "Instant shooting downstream would raise peaks.", C: "Wetlands are doing hydrologic work.", D: "Patent is legal." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The slogan ______ understaffing as a “culture issue,” which collapsed on the third double shift." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "dressed", B: "measured in headcount", C: "set to a hymn", D: "left unsaid" }, answer: "A", explain: { correct: "Dressed as means costumed as; culture-issue clothing on a staffing problem fails on a double shift.", wrong: { B: "Headcount would name staffing, not culture.", C: "Hymn is unrelated.", D: "A slogan says it." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Two labs ______ the same melting point, which made a contaminated sample in one lab less likely." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "reported", B: "invented separately as fiction", C: "sang", D: "hid" }, answer: "A", explain: { correct: "Reported the same melting point independently weakens a one-lab contamination story.", wrong: { B: "Fiction would not match across labs as measurement.", C: "Sang is unrelated.", D: "Hiding would not confirm the point." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "Painted bike stencils with unchanged turning speeds are handwriting on a fast corner. Completeness is a slower radius." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To insist that bike safety is geometry and speed, not only paint", B: "To sell paint", C: "To deny that corners have radii", D: "To teach handwriting" }, answer: "A", explain: { correct: "Stencils versus turning speeds, handwriting, slower radius.", wrong: { B: "Paint is inadequate.", C: "Radius is the needed change.", D: "Handwriting is a metaphor." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "“As we all know” is an unelected club. Leave. Ask for the page number." }], prompt: "Which choice best describes the function of the last two sentences?", choices: { A: "They instruct the reader to exit fake consensus and demand a source", B: "They explain elections", C: "They list page numbers", D: "They join the club" }, answer: "A", explain: { correct: "Leave and ask for the page number refuse “as we all know.”", wrong: { B: "Club/election is metaphorical.", C: "No list appears.", D: "Leave means do not join." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "List the hazard. List the label. List who cannot read English. A warning that assumes a language is a partial warning." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "Three lists that show how language limits safety warnings", B: "A novel about English class", C: "A hazard as golf", D: "A label as clothing" }, answer: "A", explain: { correct: "Hazard, label, who cannot read English, then partial warning.", wrong: { B: "Not a novel.", C: "Hazard means danger.", D: "Warning label, not fashion." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "A flat congestion charge is survivable because it is simple." }, { label: "Text 2", body: "Simple is not the same as fair. A night-shift nurse is not a midday shopper. Peak-only charging is harder copy and a better fit to who can actually shift a trip." }], prompt: "Text 2 would most likely", choices: { A: "trade some simplicity for a charge that tracks who can change travel time", B: "call simplicity the whole of fairness", C: "deny that nurses work nights", D: "abolish all charges and all trains" }, answer: "A", explain: { correct: "Harder copy, better fit to who can shift a trip—less simple, more fair.", wrong: { B: "Text 2 splits simple from fair.", C: "The nurse is the example.", D: "Charging remains, redesigned." } } }
  ]
},
{
  day: 60, date: "2026-11-17",
  questions: [
    { n: 1, skill: "Words in Context", texts: [{ body: "The flood gauge stayed ______, so crews used the stain line on the trestle as a backup reading." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "dark", B: "perfectly live", C: "theoretical", D: "decorative" }, answer: "A", explain: { correct: "Dark here means unpowered/off; a stain line as backup fits a dead gauge. (If “dark” feels stretched, “dead” was used earlier; “dark” as unlit/unpowered still works with stain-line backup.)", wrong: { B: "Live gauge would not need a trestle stain.", C: "Crews are in a real flood.", D: "Decorative is unrelated." } } },
    { n: 2, skill: "Words in Context", texts: [{ body: "The city ______ mural lights after bedrooms filled with glare." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "lowered", B: "raised", C: "sang", D: "ignored" }, answer: "A", explain: { correct: "Lowered lights that caused bedroom glare.", wrong: { B: "Raised would worsen glare.", C: "Sang is unrelated.", D: "They changed lights, so they did not ignore bedrooms." } } },
    { n: 3, skill: "Words in Context", texts: [{ body: "The memoir ______ the jokes without a narrator’s flinch, which lets the reader flinch instead." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "quotes", B: "censors", C: "omits", D: "hums" }, answer: "A", explain: { correct: "Quotes without a flinch transfers the flinch to the reader.", wrong: { B: "Censoring would remove the jokes.", C: "Omitting would not let the reader hear them.", D: "Hums is unrelated." } } },
    { n: 4, skill: "Words in Context", texts: [{ body: "Mangrove roots ______ nursery fish, a fact used to block a marina cut." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "harbor", B: "exclude more than open water", C: "ignore", D: "translate" }, answer: "A", explain: { correct: "Harbor means give shelter; blocking a marina to keep that nursery fits.", wrong: { B: "Excluding fish would not justify blocking a marina for them.", C: "Roots are habitat, not ignoring.", D: "Translate is language." } } },
    { n: 5, skill: "Words in Context", texts: [{ body: "The headline’s ______ of “cure” for a weak correlation prompted the authors to write in." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "use", B: "avoidance", C: "silence", D: "rhyme" }, answer: "A", explain: { correct: "Use of “cure” for a weak correlation is what prompted the letter.", wrong: { B: "Avoidance of “cure” would not prompt a protest letter about the word.", C: "A headline using “cure” is not silence.", D: "Rhyme is verse." } } },
    { n: 6, skill: "Words in Context", texts: [{ body: "Teams ______ clocks to a satellite so two traces could be laid on one timeline." }], prompt: "Which choice completes the text with the most logical and precise word or phrase?", choices: { A: "tied", B: "broke", C: "sang", D: "sold" }, answer: "A", explain: { correct: "Tied clocks to a satellite means synchronized them for one timeline.", wrong: { B: "Broke clocks would block a timeline.", C: "Sang is unrelated.", D: "Sold is commercial." } } },
    { n: 7, skill: "Text Structure and Purpose", texts: [{ body: "An unwatered green roof is a drought with a view. The plant is the maintenance, not the installation photo." }], prompt: "Which choice best states the main purpose of the text?", choices: { A: "To treat green roofs as living systems that die without care", B: "To sell views", C: "To deny that roofs can hold plants", D: "To teach photography" }, answer: "A", explain: { correct: "Unwatered, drought with a view, maintenance not photo.", wrong: { B: "View is ironic.", C: "Plants are assumed possible.", D: "Photo is the empty substitute." } } },
    { n: 8, skill: "Text Structure and Purpose", texts: [{ body: "Declaring emphasis “in original” is courtesy. Adding emphasis and skipping that note is putting words in the source’s mouth." }], prompt: "Which choice best describes the function of the last sentence?", choices: { A: "It names the dishonest counterpart to the courtesy", B: "It teaches dentistry", C: "It lists sources", D: "It praises all italics" }, answer: "A", explain: { correct: "Putting words in the source’s mouth is undisclosed added emphasis.", wrong: { B: "Mouth is idiomatic.", C: "No list appears.", D: "Undisclosed italics are criticized." } } },
    { n: 9, skill: "Text Structure and Purpose", texts: [{ body: "Ask who cleaned. Ask who is listed as author. Ask who is “technical help.” If you do not ask, credit is a caste you did not notice." }], prompt: "Which choice best describes the overall structure of the text?", choices: { A: "Three questions plus a warning about unnoticed hierarchy in credit", B: "A caste as a full history textbook", C: "A cleaning as a product ad", D: "Help as a helpline commercial" }, answer: "A", explain: { correct: "Cleaned, author, technical help, then unnoticed caste.", wrong: { B: "Caste is a metaphor.", C: "Cleaned means lab labor.", D: "Technical help is an acknowledgment category." } } },
    { n: 10, skill: "Cross-Text Connections", texts: [{ label: "Text 1", body: "Phone bans at school should be total so that every period is not a negotiation." }, { label: "Text 2", body: "Total bans that ignore medical apps will lose in practice and in fairness. Default off, written exceptions, and pouches are governance. Confiscation theater is a daily fight that still leaves the phone in the building." }], prompt: "Both authors want", choices: { A: "less chaotic, more rule-bound phone use during school", B: "more negotiation every period as the goal", C: "schools to ignore medical needs", D: "phones manufactured on campus" }, answer: "A", explain: { correct: "Text 1 hates per-period negotiation; Text 2 wants default off plus exceptions instead of theater. Shared: governed, less chaotic use.", wrong: { B: "Text 1 rejects that; Text 2 wants rules, not endless negotiation.", C: "Text 2 centers medical apps.", D: "Not manufacturing." } } }
  ]
}
);
